// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddRoleMemberApiRolesRoleIdMembersPostData, AddRoleMemberApiRolesRoleIdMembersPostErrors, AddRoleMemberApiRolesRoleIdMembersPostResponses, CreateRoleApiRolesPostData, CreateRoleApiRolesPostErrors, CreateRoleApiRolesPostResponses, CreateUserApiUsersPostData, CreateUserApiUsersPostErrors, CreateUserApiUsersPostResponses, DeleteRoleApiRolesRoleIdDeleteData, DeleteRoleApiRolesRoleIdDeleteErrors, DeleteRoleApiRolesRoleIdDeleteResponses, DeleteUserApiUsersUsernameDeleteData, DeleteUserApiUsersUsernameDeleteErrors, DeleteUserApiUsersUsernameDeleteResponses, GetChatApiChatsChatIdGetData, GetChatApiChatsChatIdGetErrors, GetChatApiChatsChatIdGetResponses, GetCurrentUserInfoApiAuthMeGetData, GetCurrentUserInfoApiAuthMeGetResponses, GetRoleApiRolesRoleIdGetData, GetRoleApiRolesRoleIdGetErrors, GetRoleApiRolesRoleIdGetResponses, GetUserApiUsersUsernameGetData, GetUserApiUsersUsernameGetErrors, GetUserApiUsersUsernameGetResponses, HealthHealthGetData, HealthHealthGetResponses, ListChatsApiChatsGetData, ListChatsApiChatsGetErrors, ListChatsApiChatsGetResponses, ListRoleMembersApiRolesRoleIdMembersGetData, ListRoleMembersApiRolesRoleIdMembersGetErrors, ListRoleMembersApiRolesRoleIdMembersGetResponses, ListRolesApiRolesGetData, ListRolesApiRolesGetErrors, ListRolesApiRolesGetResponses, ListUsersApiUsersGetData, ListUsersApiUsersGetErrors, ListUsersApiUsersGetResponses, LoginApiAuthLoginPostData, LoginApiAuthLoginPostErrors, LoginApiAuthLoginPostResponses, RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteData, RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteErrors, RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteResponses, RootGetData, RootGetResponses, UpdateRoleApiRolesRoleIdPatchData, UpdateRoleApiRolesRoleIdPatchErrors, UpdateRoleApiRolesRoleIdPatchResponses, UpdateUserApiUsersUsernamePatchData, UpdateUserApiUsersUsernamePatchErrors, UpdateUserApiUsersUsernamePatchResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Login
 *
 * Login and get JWT token.
 */
export const loginApiAuthLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginApiAuthLoginPostData, ThrowOnError>) => (options.client ?? client).post<LoginApiAuthLoginPostResponses, LoginApiAuthLoginPostErrors, ThrowOnError>({
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Current User Info
 *
 * Get current authenticated user information.
 */
export const getCurrentUserInfoApiAuthMeGet = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserInfoApiAuthMeGetData, ThrowOnError>) => (options?.client ?? client).get<GetCurrentUserInfoApiAuthMeGetResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/me',
    ...options
});

/**
 * List Users
 *
 * List all users with pagination. Admin only.
 */
export const listUsersApiUsersGet = <ThrowOnError extends boolean = false>(options?: Options<ListUsersApiUsersGetData, ThrowOnError>) => (options?.client ?? client).get<ListUsersApiUsersGetResponses, ListUsersApiUsersGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users',
    ...options
});

/**
 * Create User
 *
 * Create new user. Admin only.
 */
export const createUserApiUsersPost = <ThrowOnError extends boolean = false>(options: Options<CreateUserApiUsersPostData, ThrowOnError>) => (options.client ?? client).post<CreateUserApiUsersPostResponses, CreateUserApiUsersPostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete User
 *
 * Delete user. Admin only.
 */
export const deleteUserApiUsersUsernameDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteUserApiUsersUsernameDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteUserApiUsersUsernameDeleteResponses, DeleteUserApiUsersUsernameDeleteErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/{username}',
    ...options
});

/**
 * Get User
 *
 * Get user by username. Admin only.
 */
export const getUserApiUsersUsernameGet = <ThrowOnError extends boolean = false>(options: Options<GetUserApiUsersUsernameGetData, ThrowOnError>) => (options.client ?? client).get<GetUserApiUsersUsernameGetResponses, GetUserApiUsersUsernameGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/{username}',
    ...options
});

/**
 * Update User
 *
 * Update user. Admin only.
 */
export const updateUserApiUsersUsernamePatch = <ThrowOnError extends boolean = false>(options: Options<UpdateUserApiUsersUsernamePatchData, ThrowOnError>) => (options.client ?? client).patch<UpdateUserApiUsersUsernamePatchResponses, UpdateUserApiUsersUsernamePatchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/{username}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Chats
 *
 * List all chats with pagination. Admin only.
 */
export const listChatsApiChatsGet = <ThrowOnError extends boolean = false>(options?: Options<ListChatsApiChatsGetData, ThrowOnError>) => (options?.client ?? client).get<ListChatsApiChatsGetResponses, ListChatsApiChatsGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/chats',
    ...options
});

/**
 * Get Chat
 *
 * Get chat by ID. Admin only.
 */
export const getChatApiChatsChatIdGet = <ThrowOnError extends boolean = false>(options: Options<GetChatApiChatsChatIdGetData, ThrowOnError>) => (options.client ?? client).get<GetChatApiChatsChatIdGetResponses, GetChatApiChatsChatIdGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/chats/{chat_id}',
    ...options
});

/**
 * List Roles
 *
 * List all roles with pagination. Admin only.
 */
export const listRolesApiRolesGet = <ThrowOnError extends boolean = false>(options?: Options<ListRolesApiRolesGetData, ThrowOnError>) => (options?.client ?? client).get<ListRolesApiRolesGetResponses, ListRolesApiRolesGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/roles',
    ...options
});

/**
 * Create Role
 *
 * Create new role. Admin only.
 */
export const createRoleApiRolesPost = <ThrowOnError extends boolean = false>(options: Options<CreateRoleApiRolesPostData, ThrowOnError>) => (options.client ?? client).post<CreateRoleApiRolesPostResponses, CreateRoleApiRolesPostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/roles',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Role
 *
 * Delete role. Admin only.
 */
export const deleteRoleApiRolesRoleIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteRoleApiRolesRoleIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteRoleApiRolesRoleIdDeleteResponses, DeleteRoleApiRolesRoleIdDeleteErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/roles/{role_id}',
    ...options
});

/**
 * Get Role
 *
 * Get role by ID with its members. Admin only.
 */
export const getRoleApiRolesRoleIdGet = <ThrowOnError extends boolean = false>(options: Options<GetRoleApiRolesRoleIdGetData, ThrowOnError>) => (options.client ?? client).get<GetRoleApiRolesRoleIdGetResponses, GetRoleApiRolesRoleIdGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/roles/{role_id}',
    ...options
});

/**
 * Update Role
 *
 * Update role. Admin only.
 */
export const updateRoleApiRolesRoleIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateRoleApiRolesRoleIdPatchData, ThrowOnError>) => (options.client ?? client).patch<UpdateRoleApiRolesRoleIdPatchResponses, UpdateRoleApiRolesRoleIdPatchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/roles/{role_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Role Members
 *
 * List all members of a role. Admin only.
 */
export const listRoleMembersApiRolesRoleIdMembersGet = <ThrowOnError extends boolean = false>(options: Options<ListRoleMembersApiRolesRoleIdMembersGetData, ThrowOnError>) => (options.client ?? client).get<ListRoleMembersApiRolesRoleIdMembersGetResponses, ListRoleMembersApiRolesRoleIdMembersGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/roles/{role_id}/members',
    ...options
});

/**
 * Add Role Member
 *
 * Add member to role. Admin only.
 */
export const addRoleMemberApiRolesRoleIdMembersPost = <ThrowOnError extends boolean = false>(options: Options<AddRoleMemberApiRolesRoleIdMembersPostData, ThrowOnError>) => (options.client ?? client).post<AddRoleMemberApiRolesRoleIdMembersPostResponses, AddRoleMemberApiRolesRoleIdMembersPostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/roles/{role_id}/members',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Remove Role Member
 *
 * Remove member from role. Admin only.
 */
export const removeRoleMemberApiRolesRoleIdMembersUserIdDelete = <ThrowOnError extends boolean = false>(options: Options<RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteResponses, RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/roles/{role_id}/members/{user_id}',
    ...options
});

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Health
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });
