// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AddRoleMemberRequest
 */
export type AddRoleMemberRequest = {
    /**
     * User Id
     */
    user_id: string;
};

/**
 * ChatResponse
 */
export type ChatResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * PaginatedChatsResponse
 */
export type PaginatedChatsResponse = {
    /**
     * Items
     */
    items: Array<ChatResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PaginatedRolesResponse
 */
export type PaginatedRolesResponse = {
    /**
     * Items
     */
    items: Array<RoleResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PaginatedUsersResponse
 */
export type PaginatedUsersResponse = {
    /**
     * Items
     */
    items: Array<UserResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * RoleCreate
 */
export type RoleCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * RoleMemberResponse
 */
export type RoleMemberResponse = {
    /**
     * User Id
     */
    user_id: string;
};

/**
 * RoleResponse
 */
export type RoleResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
};

/**
 * RoleUpdate
 */
export type RoleUpdate = {
    /**
     * Name
     */
    name?: string | null;
};

/**
 * RoleWithMembersResponse
 */
export type RoleWithMembersResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
    /**
     * Members
     */
    members: Array<RoleMemberResponse>;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Is Active
     */
    is_active?: boolean;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Username
     */
    username?: string | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type LoginApiAuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginApiAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiAuthLoginPostError = LoginApiAuthLoginPostErrors[keyof LoginApiAuthLoginPostErrors];

export type LoginApiAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginApiAuthLoginPostResponse = LoginApiAuthLoginPostResponses[keyof LoginApiAuthLoginPostResponses];

export type GetCurrentUserInfoApiAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetCurrentUserInfoApiAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetCurrentUserInfoApiAuthMeGetResponse = GetCurrentUserInfoApiAuthMeGetResponses[keyof GetCurrentUserInfoApiAuthMeGetResponses];

export type ListUsersApiUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
    };
    url: '/api/users';
};

export type ListUsersApiUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListUsersApiUsersGetError = ListUsersApiUsersGetErrors[keyof ListUsersApiUsersGetErrors];

export type ListUsersApiUsersGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedUsersResponse;
};

export type ListUsersApiUsersGetResponse = ListUsersApiUsersGetResponses[keyof ListUsersApiUsersGetResponses];

export type CreateUserApiUsersPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type CreateUserApiUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserApiUsersPostError = CreateUserApiUsersPostErrors[keyof CreateUserApiUsersPostErrors];

export type CreateUserApiUsersPostResponses = {
    /**
     * Successful Response
     */
    201: UserResponse;
};

export type CreateUserApiUsersPostResponse = CreateUserApiUsersPostResponses[keyof CreateUserApiUsersPostResponses];

export type DeleteUserApiUsersUsernameDeleteData = {
    body?: never;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/api/users/{username}';
};

export type DeleteUserApiUsersUsernameDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserApiUsersUsernameDeleteError = DeleteUserApiUsersUsernameDeleteErrors[keyof DeleteUserApiUsersUsernameDeleteErrors];

export type DeleteUserApiUsersUsernameDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteUserApiUsersUsernameDeleteResponse = DeleteUserApiUsersUsernameDeleteResponses[keyof DeleteUserApiUsersUsernameDeleteResponses];

export type GetUserApiUsersUsernameGetData = {
    body?: never;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/api/users/{username}';
};

export type GetUserApiUsersUsernameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserApiUsersUsernameGetError = GetUserApiUsersUsernameGetErrors[keyof GetUserApiUsersUsernameGetErrors];

export type GetUserApiUsersUsernameGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetUserApiUsersUsernameGetResponse = GetUserApiUsersUsernameGetResponses[keyof GetUserApiUsersUsernameGetResponses];

export type UpdateUserApiUsersUsernamePatchData = {
    body: UserUpdate;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/api/users/{username}';
};

export type UpdateUserApiUsersUsernamePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserApiUsersUsernamePatchError = UpdateUserApiUsersUsernamePatchErrors[keyof UpdateUserApiUsersUsernamePatchErrors];

export type UpdateUserApiUsersUsernamePatchResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type UpdateUserApiUsersUsernamePatchResponse = UpdateUserApiUsersUsernamePatchResponses[keyof UpdateUserApiUsersUsernamePatchResponses];

export type ListChatsApiChatsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
    };
    url: '/api/chats';
};

export type ListChatsApiChatsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListChatsApiChatsGetError = ListChatsApiChatsGetErrors[keyof ListChatsApiChatsGetErrors];

export type ListChatsApiChatsGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedChatsResponse;
};

export type ListChatsApiChatsGetResponse = ListChatsApiChatsGetResponses[keyof ListChatsApiChatsGetResponses];

export type GetChatApiChatsChatIdGetData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/api/chats/{chat_id}';
};

export type GetChatApiChatsChatIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChatApiChatsChatIdGetError = GetChatApiChatsChatIdGetErrors[keyof GetChatApiChatsChatIdGetErrors];

export type GetChatApiChatsChatIdGetResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type GetChatApiChatsChatIdGetResponse = GetChatApiChatsChatIdGetResponses[keyof GetChatApiChatsChatIdGetResponses];

export type ListRolesApiRolesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
    };
    url: '/api/roles';
};

export type ListRolesApiRolesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRolesApiRolesGetError = ListRolesApiRolesGetErrors[keyof ListRolesApiRolesGetErrors];

export type ListRolesApiRolesGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedRolesResponse;
};

export type ListRolesApiRolesGetResponse = ListRolesApiRolesGetResponses[keyof ListRolesApiRolesGetResponses];

export type CreateRoleApiRolesPostData = {
    body: RoleCreate;
    path?: never;
    query?: never;
    url: '/api/roles';
};

export type CreateRoleApiRolesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRoleApiRolesPostError = CreateRoleApiRolesPostErrors[keyof CreateRoleApiRolesPostErrors];

export type CreateRoleApiRolesPostResponses = {
    /**
     * Successful Response
     */
    201: RoleResponse;
};

export type CreateRoleApiRolesPostResponse = CreateRoleApiRolesPostResponses[keyof CreateRoleApiRolesPostResponses];

export type DeleteRoleApiRolesRoleIdDeleteData = {
    body?: never;
    path: {
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/roles/{role_id}';
};

export type DeleteRoleApiRolesRoleIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRoleApiRolesRoleIdDeleteError = DeleteRoleApiRolesRoleIdDeleteErrors[keyof DeleteRoleApiRolesRoleIdDeleteErrors];

export type DeleteRoleApiRolesRoleIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteRoleApiRolesRoleIdDeleteResponse = DeleteRoleApiRolesRoleIdDeleteResponses[keyof DeleteRoleApiRolesRoleIdDeleteResponses];

export type GetRoleApiRolesRoleIdGetData = {
    body?: never;
    path: {
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/roles/{role_id}';
};

export type GetRoleApiRolesRoleIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRoleApiRolesRoleIdGetError = GetRoleApiRolesRoleIdGetErrors[keyof GetRoleApiRolesRoleIdGetErrors];

export type GetRoleApiRolesRoleIdGetResponses = {
    /**
     * Successful Response
     */
    200: RoleWithMembersResponse;
};

export type GetRoleApiRolesRoleIdGetResponse = GetRoleApiRolesRoleIdGetResponses[keyof GetRoleApiRolesRoleIdGetResponses];

export type UpdateRoleApiRolesRoleIdPatchData = {
    body: RoleUpdate;
    path: {
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/roles/{role_id}';
};

export type UpdateRoleApiRolesRoleIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateRoleApiRolesRoleIdPatchError = UpdateRoleApiRolesRoleIdPatchErrors[keyof UpdateRoleApiRolesRoleIdPatchErrors];

export type UpdateRoleApiRolesRoleIdPatchResponses = {
    /**
     * Successful Response
     */
    200: RoleResponse;
};

export type UpdateRoleApiRolesRoleIdPatchResponse = UpdateRoleApiRolesRoleIdPatchResponses[keyof UpdateRoleApiRolesRoleIdPatchResponses];

export type ListRoleMembersApiRolesRoleIdMembersGetData = {
    body?: never;
    path: {
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/roles/{role_id}/members';
};

export type ListRoleMembersApiRolesRoleIdMembersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRoleMembersApiRolesRoleIdMembersGetError = ListRoleMembersApiRolesRoleIdMembersGetErrors[keyof ListRoleMembersApiRolesRoleIdMembersGetErrors];

export type ListRoleMembersApiRolesRoleIdMembersGetResponses = {
    /**
     * Response List Role Members Api Roles  Role Id  Members Get
     *
     * Successful Response
     */
    200: Array<RoleMemberResponse>;
};

export type ListRoleMembersApiRolesRoleIdMembersGetResponse = ListRoleMembersApiRolesRoleIdMembersGetResponses[keyof ListRoleMembersApiRolesRoleIdMembersGetResponses];

export type AddRoleMemberApiRolesRoleIdMembersPostData = {
    body: AddRoleMemberRequest;
    path: {
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/roles/{role_id}/members';
};

export type AddRoleMemberApiRolesRoleIdMembersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddRoleMemberApiRolesRoleIdMembersPostError = AddRoleMemberApiRolesRoleIdMembersPostErrors[keyof AddRoleMemberApiRolesRoleIdMembersPostErrors];

export type AddRoleMemberApiRolesRoleIdMembersPostResponses = {
    /**
     * Successful Response
     */
    201: RoleMemberResponse;
};

export type AddRoleMemberApiRolesRoleIdMembersPostResponse = AddRoleMemberApiRolesRoleIdMembersPostResponses[keyof AddRoleMemberApiRolesRoleIdMembersPostResponses];

export type RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * Role Id
         */
        role_id: string;
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/roles/{role_id}/members/{user_id}';
};

export type RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteError = RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteErrors[keyof RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteErrors];

export type RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteResponse = RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteResponses[keyof RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
