// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {})
}

/**
 * ActivityPoint
 *
 * Число действий за один день.
 */
export type ActivityPoint = {
  /**
   * Date
   */
  date: string
  /**
   * Count
   */
  count: number
}

/**
 * ActorType
 *
 * Кто совершил действие.
 */
export type ActorType = 'user' | 'bot' | 'system' | 'external'

/**
 * AddRoleMemberRequest
 */
export type AddRoleMemberRequest = {
  /**
   * User Id
   */
  user_id: string
}

/**
 * AgentMessageResponse
 *
 * Сообщение диалога.
 *
 * ``raw`` наружу не отдаётся никогда: там лежит полный запрос к модели
 * вместе с автоконтекстом.
 */
export type AgentMessageResponse = {
  /**
   * Id
   */
  id: number
  /**
   * Role
   */
  role: string
  /**
   * Content
   */
  content: string | null
  /**
   * Tool Name
   */
  tool_name: string | null
  /**
   * Created At
   */
  created_at: string
}

/**
 * AgentSessionDetailResponse
 *
 * Сессия целиком, с ходом диалога.
 */
export type AgentSessionDetailResponse = {
  session: AgentSessionResponse
  /**
   * Messages
   */
  messages: Array<AgentMessageResponse>
}

/**
 * AgentSessionResponse
 *
 * Сессия в списке.
 */
export type AgentSessionResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Chat Id
   */
  chat_id: string
  /**
   * Chat Title
   */
  chat_title: string | null
  /**
   * User Id
   */
  user_id: string
  /**
   * User Name
   */
  user_name: string
  /**
   * Thread Id
   */
  thread_id: string | null
  status: SessionStatus
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
  /**
   * Tokens In
   */
  tokens_in: number
  /**
   * Tokens Out
   */
  tokens_out: number
  /**
   * Question
   */
  question: string | null
}

/**
 * AgentStatusResponse
 *
 * Состояние агента: включён ли и с какими лимитами.
 */
export type AgentStatusResponse = {
  /**
   * Configured
   */
  configured: boolean
  /**
   * Enabled
   */
  enabled: boolean
  /**
   * Model
   */
  model: string
  /**
   * Max Steps
   */
  max_steps: number
  /**
   * Context Messages
   */
  context_messages: number
  /**
   * Daily Token Budget
   */
  daily_token_budget: number
  /**
   * Retention Days
   */
  retention_days: number
}

/**
 * AgentUsageActor
 *
 * Расход по участнику или чату.
 */
export type AgentUsageActor = {
  /**
   * Id
   */
  id: string
  /**
   * Name
   */
  name: string
  /**
   * Sessions
   */
  sessions: number
  /**
   * Tokens
   */
  tokens: number
}

/**
 * AgentUsagePoint
 *
 * Расход за один день.
 */
export type AgentUsagePoint = {
  /**
   * Date
   */
  date: string
  /**
   * Sessions
   */
  sessions: number
  /**
   * Tokens
   */
  tokens: number
}

/**
 * AgentUsageResponse
 *
 * Расход токенов.
 *
 * Админ видит всех, обычный участник — только себя: вопрос к агенту
 * говорит о человеке не меньше, чем сам ответ.
 */
export type AgentUsageResponse = {
  /**
   * Days
   */
  days: number
  totals: AgentUsageTotals
  /**
   * By Day
   */
  by_day: Array<AgentUsagePoint>
  /**
   * Top Users
   */
  top_users: Array<AgentUsageActor>
  /**
   * Top Chats
   */
  top_chats: Array<AgentUsageActor>
  /**
   * Daily Token Budget
   */
  daily_token_budget: number
  /**
   * Spent Today
   */
  spent_today: number
}

/**
 * AgentUsageTotals
 *
 * Итоги за период.
 */
export type AgentUsageTotals = {
  /**
   * Sessions
   */
  sessions: number
  /**
   * Tokens In
   */
  tokens_in: number
  /**
   * Tokens Out
   */
  tokens_out: number
  /**
   * Users
   */
  users: number
  /**
   * Failed
   */
  failed: number
}

/**
 * BotSettingsResponse
 *
 * Bot settings response schema.
 */
export type BotSettingsResponse = {
  /**
   * Key
   */
  key: string
  /**
   * Value
   */
  value: string
  /**
   * Description
   */
  description?: string | null
  /**
   * Updated At
   */
  updated_at: string
}

/**
 * ChatDetailResponse
 *
 * Чат на своей странице — со счётчиками для подписей разделов.
 */
export type ChatDetailResponse = {
  /**
   * Id
   */
  id: string
  type: ChatType
  /**
   * Title
   */
  title?: string | null
  /**
   * About
   */
  about: string | null
  /**
   * Rules
   */
  rules: string | null
  /**
   * Invite Link
   */
  invite_link: string | null
  /**
   * Public
   */
  public: boolean | null
  /**
   * Join Moderation
   */
  join_moderation: boolean | null
  /**
   * Member Count
   */
  member_count: number
  /**
   * Webhook Count
   */
  webhook_count: number
}

/**
 * ChatResponse
 */
export type ChatResponse = {
  /**
   * Id
   */
  id: string
  type: ChatType
  /**
   * Title
   */
  title?: string | null
  /**
   * About
   */
  about: string | null
  /**
   * Rules
   */
  rules: string | null
  /**
   * Invite Link
   */
  invite_link: string | null
  /**
   * Public
   */
  public: boolean | null
  /**
   * Join Moderation
   */
  join_moderation: boolean | null
}

/**
 * ChatType
 *
 * ChatType.
 */
export type ChatType = 'private' | 'group' | 'channel'

/**
 * ChatUserChatResponse
 */
export type ChatUserChatResponse = {
  /**
   * Id
   */
  id: string
  type: ChatType
  /**
   * Title
   */
  title?: string | null
}

/**
 * ChatUserDetailResponse
 */
export type ChatUserDetailResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Is Superuser
   */
  is_superuser: boolean
  /**
   * Is Bot
   */
  is_bot: boolean
  /**
   * First Name
   */
  first_name?: string | null
  /**
   * Last Name
   */
  last_name?: string | null
  /**
   * Nick
   */
  nick?: string | null
  /**
   * About
   */
  about: string | null
  /**
   * Photo Url
   */
  photo_url: string | null
  /**
   * Roles
   */
  roles: Array<ChatUserRoleResponse>
  /**
   * Chats
   */
  chats: Array<ChatUserChatResponse>
  /**
   * Is Owner
   *
   * Пользователь — владелец бота (``OWNER_ID``).
   */
  readonly is_owner: boolean
  /**
   * Display Name
   *
   * Имя для показа. Пока имя неизвестно — остаётся ``id``.
   */
  readonly display_name: string
}

/**
 * ChatUserResponse
 *
 * Участник в списке — со ролями, чтобы список отвечал на «у кого что».
 */
export type ChatUserResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Is Superuser
   */
  is_superuser: boolean
  /**
   * Is Bot
   */
  is_bot: boolean
  /**
   * First Name
   */
  first_name?: string | null
  /**
   * Last Name
   */
  last_name?: string | null
  /**
   * Nick
   */
  nick?: string | null
  /**
   * About
   */
  about: string | null
  /**
   * Photo Url
   */
  photo_url: string | null
  /**
   * Roles
   */
  roles: Array<ChatUserRoleResponse>
  /**
   * Is Owner
   *
   * Пользователь — владелец бота (``OWNER_ID``).
   */
  readonly is_owner: boolean
  /**
   * Display Name
   *
   * Имя для показа. Пока имя неизвестно — остаётся ``id``.
   */
  readonly display_name: string
}

/**
 * ChatUserRoleResponse
 */
export type ChatUserRoleResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Name
   */
  name: string
}

/**
 * EventResponse
 *
 * Событие в ленте.
 */
export type EventResponse = {
  /**
   * Id
   */
  id: number
  /**
   * Ts
   */
  ts: string
  /**
   * Type
   */
  type: string
  source: EventSource
  severity: EventSeverity
  actor_type: ActorType
  /**
   * Actor Id
   */
  actor_id: string | null
  /**
   * Chat Id
   */
  chat_id: string | null
  /**
   * Entity Type
   */
  entity_type: string | null
  /**
   * Entity Id
   */
  entity_id: string | null
  /**
   * Summary
   */
  summary: string
  /**
   * Payload
   */
  payload: {
    [key: string]: unknown
  } | null
  /**
   * Trace Id
   */
  trace_id: string | null
}

/**
 * EventSeverity
 *
 * Значимость события — ею подсвечивается строка в панели.
 */
export type EventSeverity = 'debug' | 'info' | 'warning' | 'error'

/**
 * EventSource
 *
 * Откуда пришло действие.
 *
 * Актор не отвечает на этот вопрос: один и тот же человек назначает роль
 * и командой в чате, и кнопкой в панели.
 */
export type EventSource = 'panel' | 'command' | 'api' | 'bot' | 'webhook' | 'plugin' | 'system'

/**
 * EventTypeResponse
 *
 * Тип события из реестра — панель строит по нему подписи и фильтры.
 */
export type EventTypeResponse = {
  /**
   * Type
   */
  type: string
  /**
   * Title
   */
  title: string
  source: EventSource
  severity: EventSeverity
  /**
   * Persist
   */
  persist: boolean
  /**
   * Chat Scoped
   */
  chat_scoped: boolean
}

/**
 * GlWebhookCreate
 *
 * Create GitLab Webhook schema.
 */
export type GlWebhookCreate = {
  /**
   * Name
   */
  name?: string
  /**
   * Secret
   */
  secret: string
  /**
   * Chat Id
   */
  chat_id: string
}

/**
 * GlWebhookListResponse
 *
 * List response for webhooks.
 */
export type GlWebhookListResponse = {
  /**
   * Items
   */
  items: Array<GlWebhookRead>
  /**
   * Total
   */
  total: number
  /**
   * Page
   */
  page: number
  /**
   * Size
   */
  size: number
  /**
   * Pages
   */
  pages: number
}

/**
 * GlWebhookRead
 *
 * Read GitLab Webhook schema.
 */
export type GlWebhookRead = {
  /**
   * Name
   */
  name?: string
  /**
   * Id
   */
  id: string
  /**
   * Chat Id
   */
  chat_id: string
  /**
   * Chat Title
   */
  chat_title?: string | null
  /**
   * Created By Id
   */
  created_by_id: string
  /**
   * Created By Name
   */
  created_by_name?: string | null
  /**
   * Last Used At
   */
  last_used_at: string | null
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
}

/**
 * GlWebhookUpdate
 *
 * Update GitLab Webhook schema.
 */
export type GlWebhookUpdate = {
  /**
   * Name
   */
  name?: string | null
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * OverviewCounts
 *
 * Счётчики для плиток обзора.
 */
export type OverviewCounts = {
  /**
   * Chats
   */
  chats: number
  /**
   * Chat Users
   */
  chat_users: number
  /**
   * Roles
   */
  roles: number
  /**
   * Webhooks
   */
  webhooks: number
  /**
   * Webhooks Active
   */
  webhooks_active: number
}

/**
 * OverviewResponse
 */
export type OverviewResponse = {
  counts: OverviewCounts
  /**
   * Activity
   */
  activity?: Array<ActivityPoint>
  /**
   * Activity Days
   */
  activity_days: number
}

/**
 * PaginatedAgentSessionsResponse
 *
 * Постраничный список сессий.
 */
export type PaginatedAgentSessionsResponse = {
  /**
   * Items
   */
  items: Array<AgentSessionResponse>
  /**
   * Total
   */
  total: number
  /**
   * Page
   */
  page: number
  /**
   * Size
   */
  size: number
  /**
   * Pages
   */
  pages: number
}

/**
 * PaginatedChatUsersResponse
 */
export type PaginatedChatUsersResponse = {
  /**
   * Items
   */
  items: Array<ChatUserResponse>
  /**
   * Total
   */
  total: number
  /**
   * Page
   */
  page: number
  /**
   * Size
   */
  size: number
  /**
   * Pages
   */
  pages: number
}

/**
 * PaginatedChatsResponse
 */
export type PaginatedChatsResponse = {
  /**
   * Items
   */
  items: Array<ChatResponse>
  /**
   * Total
   */
  total: number
  /**
   * Page
   */
  page: number
  /**
   * Size
   */
  size: number
  /**
   * Pages
   */
  pages: number
}

/**
 * PaginatedEventsResponse
 *
 * Постраничный ответ ленты.
 */
export type PaginatedEventsResponse = {
  /**
   * Items
   */
  items: Array<EventResponse>
  /**
   * Total
   */
  total: number
  /**
   * Page
   */
  page: number
  /**
   * Size
   */
  size: number
  /**
   * Pages
   */
  pages: number
}

/**
 * PaginatedRolesResponse
 */
export type PaginatedRolesResponse = {
  /**
   * Items
   */
  items: Array<RoleResponse>
  /**
   * Total
   */
  total: number
  /**
   * Page
   */
  page: number
  /**
   * Size
   */
  size: number
  /**
   * Pages
   */
  pages: number
}

/**
 * RoleCreate
 */
export type RoleCreate = {
  /**
   * Name
   */
  name: string
}

/**
 * RoleMemberResponse
 */
export type RoleMemberResponse = {
  /**
   * User Id
   */
  user_id: string
  /**
   * Display Name
   */
  display_name: string
  /**
   * Is Bot
   */
  is_bot: boolean
  /**
   * Photo Url
   */
  photo_url: string | null
}

/**
 * RoleResponse
 */
export type RoleResponse = {
  /**
   * Name
   */
  name: string
  /**
   * Id
   */
  id: string
  /**
   * Member Count
   */
  member_count: number
}

/**
 * RoleUpdate
 */
export type RoleUpdate = {
  /**
   * Name
   */
  name?: string | null
}

/**
 * RoleWithMembersResponse
 */
export type RoleWithMembersResponse = {
  /**
   * Name
   */
  name: string
  /**
   * Id
   */
  id: string
  /**
   * Member Count
   */
  member_count: number
  /**
   * Members
   */
  members: Array<RoleMemberResponse>
}

/**
 * SendMessageRequest
 */
export type SendMessageRequest = {
  /**
   * Text
   *
   * Message text to send
   */
  text: string
  /**
   * Parse Mode
   *
   * Parse mode for message formatting
   */
  parse_mode?: 'MarkdownV2' | 'HTML' | null
}

/**
 * SendMessageResponse
 */
export type SendMessageResponse = {
  /**
   * Success
   */
  success: boolean
  /**
   * Message
   */
  message: string
}

/**
 * SessionStatus
 *
 * Состояние сессии.
 */
export type SessionStatus = 'active' | 'waiting_approval' | 'done' | 'failed' | 'canceled'

/**
 * Token
 */
export type Token = {
  /**
   * Access Token
   */
  access_token: string
  /**
   * Token Type
   */
  token_type?: string
}

/**
 * TokenLoginRequest
 */
export type TokenLoginRequest = {
  /**
   * Token
   */
  token: string
}

/**
 * UpdateBotSettingsRequest
 *
 * Update bot settings request schema.
 */
export type UpdateBotSettingsRequest = {
  /**
   * Value
   */
  value: string
  /**
   * Description
   */
  description?: string | null
}

/**
 * UpdateChatUserRequest
 */
export type UpdateChatUserRequest = {
  /**
   * Is Superuser
   */
  is_superuser: boolean
}

/**
 * UserResponse
 *
 * Текущий пользователь панели.
 */
export type UserResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Is Superuser
   */
  is_superuser: boolean
  /**
   * Is Bot
   */
  is_bot: boolean
  /**
   * First Name
   */
  first_name?: string | null
  /**
   * Last Name
   */
  last_name?: string | null
  /**
   * Nick
   */
  nick?: string | null
  /**
   * About
   */
  about: string | null
  /**
   * Photo Url
   */
  photo_url: string | null
  /**
   * Is Owner
   *
   * Пользователь — владелец бота (``OWNER_ID``).
   */
  readonly is_owner: boolean
  /**
   * Display Name
   *
   * Имя для показа. Пока имя неизвестно — остаётся ``id``.
   */
  readonly display_name: string
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
}

/**
 * WebhookCreateResponse
 *
 * Схема ответа при создании вебхука.
 */
export type WebhookCreateResponse = {
  webhook: WebhookResponse
  /**
   * Api Key
   *
   * API ключ для доступа к вебхуку (показывается только один раз!)
   */
  api_key: string
  /**
   * Message
   *
   * Сообщение о результате операции
   */
  message: string
}

/**
 * WebhookCreateSchema
 *
 * Схема для создания вебхука.
 */
export type WebhookCreateSchema = {
  /**
   * Name
   *
   * Название вебхука
   */
  name: string
  /**
   * Chat Id
   *
   * ID чата для отправки сообщений
   */
  chat_id: string
  /**
   * Webhook Metadata
   *
   * Дополнительные настройки вебхука
   */
  webhook_metadata?: {
    [key: string]: unknown
  }
}

/**
 * WebhookFileSchema
 *
 * Схема для файла в вебхуке.
 */
export type WebhookFileSchema = {
  /**
   * Content
   *
   * Base64 encoded file content
   */
  content?: string | null
  /**
   * Data Url
   *
   * Data URL with file content
   */
  data_url?: string | null
  /**
   * Filename
   *
   * File name
   */
  filename: string
  /**
   * Caption
   *
   * Подпись к файлу
   */
  caption?: string | null
}

/**
 * WebhookListResponse
 *
 * Схема ответа со списком вебхуков.
 */
export type WebhookListResponse = {
  /**
   * Webhooks
   */
  webhooks: Array<WebhookResponse>
  /**
   * Total
   *
   * Общее количество вебхуков
   */
  total: number
}

/**
 * WebhookRegenerateResponse
 *
 * Схема ответа при перегенерации API ключа.
 */
export type WebhookRegenerateResponse = {
  webhook: WebhookResponse
  /**
   * Api Key
   *
   * Новый API ключ для доступа к вебхуку
   */
  api_key: string
  /**
   * Message
   *
   * Сообщение о результате операции
   */
  message: string
}

/**
 * WebhookResponse
 *
 * Схема ответа с информацией о вебхуке.
 */
export type WebhookResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Name
   */
  name: string
  /**
   * Chat Id
   */
  chat_id: string
  /**
   * Created By
   */
  created_by: string
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
  /**
   * Is Active
   */
  is_active: boolean
  /**
   * Webhook Metadata
   */
  webhook_metadata: {
    [key: string]: unknown
  }
}

/**
 * WebhookSendRequest
 *
 * Схема для отправки сообщения через вебхук.
 */
export type WebhookSendRequest = {
  /**
   * Text
   *
   * Текст сообщения
   */
  text?: string | null
  /**
   * Файл для отправки
   */
  file?: WebhookFileSchema | null
  /**
   * Parse Mode
   *
   * Режим разметки текста
   */
  parse_mode?: 'MarkdownV2' | 'HTML' | null
}

/**
 * WebhookSendResponse
 *
 * Схема ответа при отправке сообщения через вебхук.
 */
export type WebhookSendResponse = {
  /**
   * Success
   *
   * Успешно ли отправлено сообщение
   */
  success: boolean
  /**
   * Message
   *
   * Сообщение о результате
   */
  message: string
  /**
   * Webhook Id
   *
   * ID вебхука
   */
  webhook_id: string
  /**
   * Chat Id
   *
   * ID чата, в который отправлено сообщение
   */
  chat_id: string
  /**
   * Msg Id
   *
   * ID отправленного сообщения
   */
  msg_id?: string | null
  /**
   * File Id
   *
   * ID загруженного файла (если отправлялся файл)
   */
  file_id?: string | null
}

/**
 * WebhookUpdateSchema
 *
 * Схема для обновления вебхука.
 */
export type WebhookUpdateSchema = {
  /**
   * Name
   *
   * Название вебхука
   */
  name?: string | null
  /**
   * Is Active
   *
   * Активен ли вебхук
   */
  is_active?: boolean | null
  /**
   * Webhook Metadata
   *
   * Дополнительные настройки вебхука
   */
  webhook_metadata?: {
    [key: string]: unknown
  } | null
}

/**
 * ChatUserDetailResponse
 */
export type ChatUserDetailResponseWritable = {
  /**
   * Id
   */
  id: string
  /**
   * Is Superuser
   */
  is_superuser: boolean
  /**
   * Is Bot
   */
  is_bot: boolean
  /**
   * First Name
   */
  first_name?: string | null
  /**
   * Last Name
   */
  last_name?: string | null
  /**
   * Nick
   */
  nick?: string | null
  /**
   * About
   */
  about: string | null
  /**
   * Photo Url
   */
  photo_url: string | null
  /**
   * Roles
   */
  roles: Array<ChatUserRoleResponse>
  /**
   * Chats
   */
  chats: Array<ChatUserChatResponse>
}

/**
 * ChatUserResponse
 *
 * Участник в списке — со ролями, чтобы список отвечал на «у кого что».
 */
export type ChatUserResponseWritable = {
  /**
   * Id
   */
  id: string
  /**
   * Is Superuser
   */
  is_superuser: boolean
  /**
   * Is Bot
   */
  is_bot: boolean
  /**
   * First Name
   */
  first_name?: string | null
  /**
   * Last Name
   */
  last_name?: string | null
  /**
   * Nick
   */
  nick?: string | null
  /**
   * About
   */
  about: string | null
  /**
   * Photo Url
   */
  photo_url: string | null
  /**
   * Roles
   */
  roles: Array<ChatUserRoleResponse>
}

/**
 * PaginatedChatUsersResponse
 */
export type PaginatedChatUsersResponseWritable = {
  /**
   * Items
   */
  items: Array<ChatUserResponseWritable>
  /**
   * Total
   */
  total: number
  /**
   * Page
   */
  page: number
  /**
   * Size
   */
  size: number
  /**
   * Pages
   */
  pages: number
}

/**
 * UserResponse
 *
 * Текущий пользователь панели.
 */
export type UserResponseWritable = {
  /**
   * Id
   */
  id: string
  /**
   * Is Superuser
   */
  is_superuser: boolean
  /**
   * Is Bot
   */
  is_bot: boolean
  /**
   * First Name
   */
  first_name?: string | null
  /**
   * Last Name
   */
  last_name?: string | null
  /**
   * Nick
   */
  nick?: string | null
  /**
   * About
   */
  about: string | null
  /**
   * Photo Url
   */
  photo_url: string | null
}

export type LoginApiAuthLoginPostData = {
  body: TokenLoginRequest
  path?: never
  query?: never
  url: '/api/auth/login'
}

export type LoginApiAuthLoginPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type LoginApiAuthLoginPostError =
  LoginApiAuthLoginPostErrors[keyof LoginApiAuthLoginPostErrors]

export type LoginApiAuthLoginPostResponses = {
  /**
   * Successful Response
   */
  200: Token
}

export type LoginApiAuthLoginPostResponse =
  LoginApiAuthLoginPostResponses[keyof LoginApiAuthLoginPostResponses]

export type GetCurrentUserInfoApiAuthMeGetData = {
  body?: never
  path?: never
  query?: never
  url: '/api/auth/me'
}

export type GetCurrentUserInfoApiAuthMeGetResponses = {
  /**
   * Successful Response
   */
  200: UserResponse
}

export type GetCurrentUserInfoApiAuthMeGetResponse =
  GetCurrentUserInfoApiAuthMeGetResponses[keyof GetCurrentUserInfoApiAuthMeGetResponses]

export type ListChatsApiChatsGetData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page
     */
    page?: number
    /**
     * Size
     */
    size?: number
    /**
     * Search
     */
    search?: string | null
  }
  url: '/api/chats'
}

export type ListChatsApiChatsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListChatsApiChatsGetError = ListChatsApiChatsGetErrors[keyof ListChatsApiChatsGetErrors]

export type ListChatsApiChatsGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedChatsResponse
}

export type ListChatsApiChatsGetResponse =
  ListChatsApiChatsGetResponses[keyof ListChatsApiChatsGetResponses]

export type GetChatApiChatsChatIdGetData = {
  body?: never
  path: {
    /**
     * Chat Id
     */
    chat_id: string
  }
  query?: never
  url: '/api/chats/{chat_id}'
}

export type GetChatApiChatsChatIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetChatApiChatsChatIdGetError =
  GetChatApiChatsChatIdGetErrors[keyof GetChatApiChatsChatIdGetErrors]

export type GetChatApiChatsChatIdGetResponses = {
  /**
   * Successful Response
   */
  200: ChatDetailResponse
}

export type GetChatApiChatsChatIdGetResponse =
  GetChatApiChatsChatIdGetResponses[keyof GetChatApiChatsChatIdGetResponses]

export type ListChatWebhooksApiChatsChatIdWebhooksGetData = {
  body?: never
  path: {
    /**
     * Chat Id
     */
    chat_id: string
  }
  query?: never
  url: '/api/chats/{chat_id}/webhooks'
}

export type ListChatWebhooksApiChatsChatIdWebhooksGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListChatWebhooksApiChatsChatIdWebhooksGetError =
  ListChatWebhooksApiChatsChatIdWebhooksGetErrors[keyof ListChatWebhooksApiChatsChatIdWebhooksGetErrors]

export type ListChatWebhooksApiChatsChatIdWebhooksGetResponses = {
  /**
   * Successful Response
   */
  200: WebhookListResponse
}

export type ListChatWebhooksApiChatsChatIdWebhooksGetResponse =
  ListChatWebhooksApiChatsChatIdWebhooksGetResponses[keyof ListChatWebhooksApiChatsChatIdWebhooksGetResponses]

export type ListChatEventsApiChatsChatIdEventsGetData = {
  body?: never
  path: {
    /**
     * Chat Id
     */
    chat_id: string
  }
  query?: {
    /**
     * Page
     */
    page?: number
    /**
     * Size
     */
    size?: number
  }
  url: '/api/chats/{chat_id}/events'
}

export type ListChatEventsApiChatsChatIdEventsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListChatEventsApiChatsChatIdEventsGetError =
  ListChatEventsApiChatsChatIdEventsGetErrors[keyof ListChatEventsApiChatsChatIdEventsGetErrors]

export type ListChatEventsApiChatsChatIdEventsGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedEventsResponse
}

export type ListChatEventsApiChatsChatIdEventsGetResponse =
  ListChatEventsApiChatsChatIdEventsGetResponses[keyof ListChatEventsApiChatsChatIdEventsGetResponses]

export type SendMessageApiChatsChatIdSendMessagePostData = {
  body: SendMessageRequest
  path: {
    /**
     * Chat Id
     */
    chat_id: string
  }
  query?: never
  url: '/api/chats/{chat_id}/send-message'
}

export type SendMessageApiChatsChatIdSendMessagePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type SendMessageApiChatsChatIdSendMessagePostError =
  SendMessageApiChatsChatIdSendMessagePostErrors[keyof SendMessageApiChatsChatIdSendMessagePostErrors]

export type SendMessageApiChatsChatIdSendMessagePostResponses = {
  /**
   * Successful Response
   */
  200: SendMessageResponse
}

export type SendMessageApiChatsChatIdSendMessagePostResponse =
  SendMessageApiChatsChatIdSendMessagePostResponses[keyof SendMessageApiChatsChatIdSendMessagePostResponses]

export type ListRolesApiRolesGetData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page
     */
    page?: number
    /**
     * Size
     */
    size?: number
  }
  url: '/api/roles'
}

export type ListRolesApiRolesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListRolesApiRolesGetError = ListRolesApiRolesGetErrors[keyof ListRolesApiRolesGetErrors]

export type ListRolesApiRolesGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedRolesResponse
}

export type ListRolesApiRolesGetResponse =
  ListRolesApiRolesGetResponses[keyof ListRolesApiRolesGetResponses]

export type CreateRoleApiRolesPostData = {
  body: RoleCreate
  path?: never
  query?: never
  url: '/api/roles'
}

export type CreateRoleApiRolesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateRoleApiRolesPostError =
  CreateRoleApiRolesPostErrors[keyof CreateRoleApiRolesPostErrors]

export type CreateRoleApiRolesPostResponses = {
  /**
   * Successful Response
   */
  201: RoleResponse
}

export type CreateRoleApiRolesPostResponse =
  CreateRoleApiRolesPostResponses[keyof CreateRoleApiRolesPostResponses]

export type DeleteRoleApiRolesRoleIdDeleteData = {
  body?: never
  path: {
    /**
     * Role Id
     */
    role_id: string
  }
  query?: never
  url: '/api/roles/{role_id}'
}

export type DeleteRoleApiRolesRoleIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteRoleApiRolesRoleIdDeleteError =
  DeleteRoleApiRolesRoleIdDeleteErrors[keyof DeleteRoleApiRolesRoleIdDeleteErrors]

export type DeleteRoleApiRolesRoleIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type DeleteRoleApiRolesRoleIdDeleteResponse =
  DeleteRoleApiRolesRoleIdDeleteResponses[keyof DeleteRoleApiRolesRoleIdDeleteResponses]

export type GetRoleApiRolesRoleIdGetData = {
  body?: never
  path: {
    /**
     * Role Id
     */
    role_id: string
  }
  query?: never
  url: '/api/roles/{role_id}'
}

export type GetRoleApiRolesRoleIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetRoleApiRolesRoleIdGetError =
  GetRoleApiRolesRoleIdGetErrors[keyof GetRoleApiRolesRoleIdGetErrors]

export type GetRoleApiRolesRoleIdGetResponses = {
  /**
   * Successful Response
   */
  200: RoleWithMembersResponse
}

export type GetRoleApiRolesRoleIdGetResponse =
  GetRoleApiRolesRoleIdGetResponses[keyof GetRoleApiRolesRoleIdGetResponses]

export type UpdateRoleApiRolesRoleIdPatchData = {
  body: RoleUpdate
  path: {
    /**
     * Role Id
     */
    role_id: string
  }
  query?: never
  url: '/api/roles/{role_id}'
}

export type UpdateRoleApiRolesRoleIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateRoleApiRolesRoleIdPatchError =
  UpdateRoleApiRolesRoleIdPatchErrors[keyof UpdateRoleApiRolesRoleIdPatchErrors]

export type UpdateRoleApiRolesRoleIdPatchResponses = {
  /**
   * Successful Response
   */
  200: RoleResponse
}

export type UpdateRoleApiRolesRoleIdPatchResponse =
  UpdateRoleApiRolesRoleIdPatchResponses[keyof UpdateRoleApiRolesRoleIdPatchResponses]

export type AddRoleMemberApiRolesRoleIdMembersPostData = {
  body: AddRoleMemberRequest
  path: {
    /**
     * Role Id
     */
    role_id: string
  }
  query?: never
  url: '/api/roles/{role_id}/members'
}

export type AddRoleMemberApiRolesRoleIdMembersPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type AddRoleMemberApiRolesRoleIdMembersPostError =
  AddRoleMemberApiRolesRoleIdMembersPostErrors[keyof AddRoleMemberApiRolesRoleIdMembersPostErrors]

export type AddRoleMemberApiRolesRoleIdMembersPostResponses = {
  /**
   * Successful Response
   */
  201: RoleMemberResponse
}

export type AddRoleMemberApiRolesRoleIdMembersPostResponse =
  AddRoleMemberApiRolesRoleIdMembersPostResponses[keyof AddRoleMemberApiRolesRoleIdMembersPostResponses]

export type RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteData = {
  body?: never
  path: {
    /**
     * Role Id
     */
    role_id: string
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: '/api/roles/{role_id}/members/{user_id}'
}

export type RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteError =
  RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteErrors[keyof RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteErrors]

export type RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteResponse =
  RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteResponses[keyof RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteResponses]

export type ListChatUsersApiChatUsersGetData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page
     */
    page?: number
    /**
     * Size
     */
    size?: number
    /**
     * Search
     */
    search?: string | null
    /**
     * Chat Id
     */
    chat_id?: string | null
  }
  url: '/api/chat-users'
}

export type ListChatUsersApiChatUsersGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListChatUsersApiChatUsersGetError =
  ListChatUsersApiChatUsersGetErrors[keyof ListChatUsersApiChatUsersGetErrors]

export type ListChatUsersApiChatUsersGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedChatUsersResponse
}

export type ListChatUsersApiChatUsersGetResponse =
  ListChatUsersApiChatUsersGetResponses[keyof ListChatUsersApiChatUsersGetResponses]

export type GetChatUserApiChatUsersUserIdGetData = {
  body?: never
  path: {
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: '/api/chat-users/{user_id}'
}

export type GetChatUserApiChatUsersUserIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetChatUserApiChatUsersUserIdGetError =
  GetChatUserApiChatUsersUserIdGetErrors[keyof GetChatUserApiChatUsersUserIdGetErrors]

export type GetChatUserApiChatUsersUserIdGetResponses = {
  /**
   * Successful Response
   */
  200: ChatUserDetailResponse
}

export type GetChatUserApiChatUsersUserIdGetResponse =
  GetChatUserApiChatUsersUserIdGetResponses[keyof GetChatUserApiChatUsersUserIdGetResponses]

export type UpdateChatUserApiChatUsersUserIdPatchData = {
  body: UpdateChatUserRequest
  path: {
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: '/api/chat-users/{user_id}'
}

export type UpdateChatUserApiChatUsersUserIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateChatUserApiChatUsersUserIdPatchError =
  UpdateChatUserApiChatUsersUserIdPatchErrors[keyof UpdateChatUserApiChatUsersUserIdPatchErrors]

export type UpdateChatUserApiChatUsersUserIdPatchResponses = {
  /**
   * Successful Response
   */
  200: ChatUserResponse
}

export type UpdateChatUserApiChatUsersUserIdPatchResponse =
  UpdateChatUserApiChatUsersUserIdPatchResponses[keyof UpdateChatUserApiChatUsersUserIdPatchResponses]

export type RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteData = {
  body?: never
  path: {
    /**
     * User Id
     */
    user_id: string
    /**
     * Role Id
     */
    role_id: string
  }
  query?: never
  url: '/api/chat-users/{user_id}/roles/{role_id}'
}

export type RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteError =
  RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteErrors[keyof RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteErrors]

export type RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteResponse =
  RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteResponses[keyof RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteResponses]

export type AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostData = {
  body?: never
  path: {
    /**
     * User Id
     */
    user_id: string
    /**
     * Role Id
     */
    role_id: string
  }
  query?: never
  url: '/api/chat-users/{user_id}/roles/{role_id}'
}

export type AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostError =
  AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostErrors[keyof AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostErrors]

export type AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostResponses = {
  /**
   * Response Assign Role To User Api Chat Users  User Id  Roles  Role Id  Post
   *
   * Successful Response
   */
  201: {
    [key: string]: string
  }
}

export type AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostResponse =
  AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostResponses[keyof AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostResponses]

export type GetBotSettingApiBotSettingsKeyGetData = {
  body?: never
  path: {
    /**
     * Key
     */
    key: string
  }
  query?: never
  url: '/api/bot-settings/{key}'
}

export type GetBotSettingApiBotSettingsKeyGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetBotSettingApiBotSettingsKeyGetError =
  GetBotSettingApiBotSettingsKeyGetErrors[keyof GetBotSettingApiBotSettingsKeyGetErrors]

export type GetBotSettingApiBotSettingsKeyGetResponses = {
  /**
   * Successful Response
   */
  200: BotSettingsResponse
}

export type GetBotSettingApiBotSettingsKeyGetResponse =
  GetBotSettingApiBotSettingsKeyGetResponses[keyof GetBotSettingApiBotSettingsKeyGetResponses]

export type UpdateBotSettingApiBotSettingsKeyPutData = {
  body: UpdateBotSettingsRequest
  path: {
    /**
     * Key
     */
    key: string
  }
  query?: never
  url: '/api/bot-settings/{key}'
}

export type UpdateBotSettingApiBotSettingsKeyPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateBotSettingApiBotSettingsKeyPutError =
  UpdateBotSettingApiBotSettingsKeyPutErrors[keyof UpdateBotSettingApiBotSettingsKeyPutErrors]

export type UpdateBotSettingApiBotSettingsKeyPutResponses = {
  /**
   * Successful Response
   */
  200: BotSettingsResponse
}

export type UpdateBotSettingApiBotSettingsKeyPutResponse =
  UpdateBotSettingApiBotSettingsKeyPutResponses[keyof UpdateBotSettingApiBotSettingsKeyPutResponses]

export type ListBotSettingsApiBotSettingsGetData = {
  body?: never
  path?: never
  query?: never
  url: '/api/bot-settings'
}

export type ListBotSettingsApiBotSettingsGetResponses = {
  /**
   * Response List Bot Settings Api Bot Settings Get
   *
   * Successful Response
   */
  200: Array<BotSettingsResponse>
}

export type ListBotSettingsApiBotSettingsGetResponse =
  ListBotSettingsApiBotSettingsGetResponses[keyof ListBotSettingsApiBotSettingsGetResponses]

export type ListEventTypesApiEventsTypesGetData = {
  body?: never
  path?: never
  query?: never
  url: '/api/events/types'
}

export type ListEventTypesApiEventsTypesGetResponses = {
  /**
   * Response List Event Types Api Events Types Get
   *
   * Successful Response
   */
  200: Array<EventTypeResponse>
}

export type ListEventTypesApiEventsTypesGetResponse =
  ListEventTypesApiEventsTypesGetResponses[keyof ListEventTypesApiEventsTypesGetResponses]

export type ListEventsApiEventsGetData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page
     */
    page?: number
    /**
     * Size
     */
    size?: number
    /**
     * Type
     */
    type?: string | null
    /**
     * Source
     */
    source?: EventSource | null
    /**
     * Severity
     */
    severity?: EventSeverity | null
    /**
     * Actor Id
     */
    actor_id?: string | null
    /**
     * Chat Id
     */
    chat_id?: string | null
    /**
     * Entity Type
     */
    entity_type?: string | null
    /**
     * Entity Id
     */
    entity_id?: string | null
    /**
     * Start Date
     */
    start_date?: string | null
    /**
     * End Date
     */
    end_date?: string | null
    /**
     * Search Query
     */
    search_query?: string | null
  }
  url: '/api/events'
}

export type ListEventsApiEventsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListEventsApiEventsGetError =
  ListEventsApiEventsGetErrors[keyof ListEventsApiEventsGetErrors]

export type ListEventsApiEventsGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedEventsResponse
}

export type ListEventsApiEventsGetResponse =
  ListEventsApiEventsGetResponses[keyof ListEventsApiEventsGetResponses]

export type GetEventApiEventsEventIdGetData = {
  body?: never
  path: {
    /**
     * Event Id
     */
    event_id: number
  }
  query?: never
  url: '/api/events/{event_id}'
}

export type GetEventApiEventsEventIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetEventApiEventsEventIdGetError =
  GetEventApiEventsEventIdGetErrors[keyof GetEventApiEventsEventIdGetErrors]

export type GetEventApiEventsEventIdGetResponses = {
  /**
   * Successful Response
   */
  200: EventResponse
}

export type GetEventApiEventsEventIdGetResponse =
  GetEventApiEventsEventIdGetResponses[keyof GetEventApiEventsEventIdGetResponses]

export type GetOverviewApiOverviewGetData = {
  body?: never
  path?: never
  query?: {
    /**
     * Days
     */
    days?: number
  }
  url: '/api/overview'
}

export type GetOverviewApiOverviewGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetOverviewApiOverviewGetError =
  GetOverviewApiOverviewGetErrors[keyof GetOverviewApiOverviewGetErrors]

export type GetOverviewApiOverviewGetResponses = {
  /**
   * Successful Response
   */
  200: OverviewResponse
}

export type GetOverviewApiOverviewGetResponse =
  GetOverviewApiOverviewGetResponses[keyof GetOverviewApiOverviewGetResponses]

export type ListWebhooksApiWebhooksGetData = {
  body?: never
  path?: never
  query?: never
  url: '/api/webhooks'
}

export type ListWebhooksApiWebhooksGetResponses = {
  /**
   * Successful Response
   */
  200: WebhookListResponse
}

export type ListWebhooksApiWebhooksGetResponse =
  ListWebhooksApiWebhooksGetResponses[keyof ListWebhooksApiWebhooksGetResponses]

export type CreateWebhookApiWebhooksPostData = {
  body: WebhookCreateSchema
  path?: never
  query?: never
  url: '/api/webhooks'
}

export type CreateWebhookApiWebhooksPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateWebhookApiWebhooksPostError =
  CreateWebhookApiWebhooksPostErrors[keyof CreateWebhookApiWebhooksPostErrors]

export type CreateWebhookApiWebhooksPostResponses = {
  /**
   * Successful Response
   */
  200: WebhookCreateResponse
}

export type CreateWebhookApiWebhooksPostResponse =
  CreateWebhookApiWebhooksPostResponses[keyof CreateWebhookApiWebhooksPostResponses]

export type DeleteWebhookApiWebhooksWebhookIdDeleteData = {
  body?: never
  path: {
    /**
     * Webhook Id
     */
    webhook_id: string
  }
  query?: never
  url: '/api/webhooks/{webhook_id}'
}

export type DeleteWebhookApiWebhooksWebhookIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteWebhookApiWebhooksWebhookIdDeleteError =
  DeleteWebhookApiWebhooksWebhookIdDeleteErrors[keyof DeleteWebhookApiWebhooksWebhookIdDeleteErrors]

export type DeleteWebhookApiWebhooksWebhookIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type DeleteWebhookApiWebhooksWebhookIdDeleteResponse =
  DeleteWebhookApiWebhooksWebhookIdDeleteResponses[keyof DeleteWebhookApiWebhooksWebhookIdDeleteResponses]

export type GetWebhookApiWebhooksWebhookIdGetData = {
  body?: never
  path: {
    /**
     * Webhook Id
     */
    webhook_id: string
  }
  query?: never
  url: '/api/webhooks/{webhook_id}'
}

export type GetWebhookApiWebhooksWebhookIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetWebhookApiWebhooksWebhookIdGetError =
  GetWebhookApiWebhooksWebhookIdGetErrors[keyof GetWebhookApiWebhooksWebhookIdGetErrors]

export type GetWebhookApiWebhooksWebhookIdGetResponses = {
  /**
   * Successful Response
   */
  200: WebhookResponse
}

export type GetWebhookApiWebhooksWebhookIdGetResponse =
  GetWebhookApiWebhooksWebhookIdGetResponses[keyof GetWebhookApiWebhooksWebhookIdGetResponses]

export type UpdateWebhookApiWebhooksWebhookIdPutData = {
  body: WebhookUpdateSchema
  path: {
    /**
     * Webhook Id
     */
    webhook_id: string
  }
  query?: never
  url: '/api/webhooks/{webhook_id}'
}

export type UpdateWebhookApiWebhooksWebhookIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateWebhookApiWebhooksWebhookIdPutError =
  UpdateWebhookApiWebhooksWebhookIdPutErrors[keyof UpdateWebhookApiWebhooksWebhookIdPutErrors]

export type UpdateWebhookApiWebhooksWebhookIdPutResponses = {
  /**
   * Successful Response
   */
  200: WebhookResponse
}

export type UpdateWebhookApiWebhooksWebhookIdPutResponse =
  UpdateWebhookApiWebhooksWebhookIdPutResponses[keyof UpdateWebhookApiWebhooksWebhookIdPutResponses]

export type RegenerateWebhookApiKeyApiWebhooksWebhookIdRegeneratePostData = {
  body?: never
  path: {
    /**
     * Webhook Id
     */
    webhook_id: string
  }
  query?: never
  url: '/api/webhooks/{webhook_id}/regenerate'
}

export type RegenerateWebhookApiKeyApiWebhooksWebhookIdRegeneratePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type RegenerateWebhookApiKeyApiWebhooksWebhookIdRegeneratePostError =
  RegenerateWebhookApiKeyApiWebhooksWebhookIdRegeneratePostErrors[keyof RegenerateWebhookApiKeyApiWebhooksWebhookIdRegeneratePostErrors]

export type RegenerateWebhookApiKeyApiWebhooksWebhookIdRegeneratePostResponses = {
  /**
   * Successful Response
   */
  200: WebhookRegenerateResponse
}

export type RegenerateWebhookApiKeyApiWebhooksWebhookIdRegeneratePostResponse =
  RegenerateWebhookApiKeyApiWebhooksWebhookIdRegeneratePostResponses[keyof RegenerateWebhookApiKeyApiWebhooksWebhookIdRegeneratePostResponses]

export type HandleWebhookWebhooksWebhookIdPostData = {
  body: WebhookSendRequest
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
  }
  path: {
    /**
     * Webhook Id
     */
    webhook_id: string
  }
  query?: never
  url: '/webhooks/{webhook_id}'
}

export type HandleWebhookWebhooksWebhookIdPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type HandleWebhookWebhooksWebhookIdPostError =
  HandleWebhookWebhooksWebhookIdPostErrors[keyof HandleWebhookWebhooksWebhookIdPostErrors]

export type HandleWebhookWebhooksWebhookIdPostResponses = {
  /**
   * Successful Response
   */
  200: WebhookSendResponse
}

export type HandleWebhookWebhooksWebhookIdPostResponse =
  HandleWebhookWebhooksWebhookIdPostResponses[keyof HandleWebhookWebhooksWebhookIdPostResponses]

export type RootGetData = {
  body?: never
  path?: never
  query?: never
  url: '/'
}

export type RootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type HealthHealthGetData = {
  body?: never
  path?: never
  query?: never
  url: '/health'
}

export type HealthHealthGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type GetStatusApiAiStatusGetData = {
  body?: never
  path?: never
  query?: never
  url: '/api/ai/status'
}

export type GetStatusApiAiStatusGetResponses = {
  /**
   * Successful Response
   */
  200: AgentStatusResponse
}

export type GetStatusApiAiStatusGetResponse =
  GetStatusApiAiStatusGetResponses[keyof GetStatusApiAiStatusGetResponses]

export type ListSessionsApiAiSessionsGetData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page
     */
    page?: number
    /**
     * Size
     */
    size?: number
    /**
     * User Id
     */
    user_id?: string | null
    /**
     * Chat Id
     */
    chat_id?: string | null
    /**
     * Session Status
     */
    session_status?: SessionStatus | null
    /**
     * Start Date
     */
    start_date?: string | null
    /**
     * End Date
     */
    end_date?: string | null
  }
  url: '/api/ai/sessions'
}

export type ListSessionsApiAiSessionsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListSessionsApiAiSessionsGetError =
  ListSessionsApiAiSessionsGetErrors[keyof ListSessionsApiAiSessionsGetErrors]

export type ListSessionsApiAiSessionsGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedAgentSessionsResponse
}

export type ListSessionsApiAiSessionsGetResponse =
  ListSessionsApiAiSessionsGetResponses[keyof ListSessionsApiAiSessionsGetResponses]

export type GetSessionApiAiSessionsSessionIdGetData = {
  body?: never
  path: {
    /**
     * Session Id
     */
    session_id: string
  }
  query?: never
  url: '/api/ai/sessions/{session_id}'
}

export type GetSessionApiAiSessionsSessionIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetSessionApiAiSessionsSessionIdGetError =
  GetSessionApiAiSessionsSessionIdGetErrors[keyof GetSessionApiAiSessionsSessionIdGetErrors]

export type GetSessionApiAiSessionsSessionIdGetResponses = {
  /**
   * Successful Response
   */
  200: AgentSessionDetailResponse
}

export type GetSessionApiAiSessionsSessionIdGetResponse =
  GetSessionApiAiSessionsSessionIdGetResponses[keyof GetSessionApiAiSessionsSessionIdGetResponses]

export type GetUsageApiAiUsageGetData = {
  body?: never
  path?: never
  query?: {
    /**
     * Days
     */
    days?: number
  }
  url: '/api/ai/usage'
}

export type GetUsageApiAiUsageGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetUsageApiAiUsageGetError =
  GetUsageApiAiUsageGetErrors[keyof GetUsageApiAiUsageGetErrors]

export type GetUsageApiAiUsageGetResponses = {
  /**
   * Successful Response
   */
  200: AgentUsageResponse
}

export type GetUsageApiAiUsageGetResponse =
  GetUsageApiAiUsageGetResponses[keyof GetUsageApiAiUsageGetResponses]

export type ListWebhooksGlWebhooksGetData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page
     */
    page?: number
    /**
     * Size
     */
    size?: number
  }
  url: '/gl/webhooks'
}

export type ListWebhooksGlWebhooksGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListWebhooksGlWebhooksGetError =
  ListWebhooksGlWebhooksGetErrors[keyof ListWebhooksGlWebhooksGetErrors]

export type ListWebhooksGlWebhooksGetResponses = {
  /**
   * Successful Response
   */
  200: GlWebhookListResponse
}

export type ListWebhooksGlWebhooksGetResponse =
  ListWebhooksGlWebhooksGetResponses[keyof ListWebhooksGlWebhooksGetResponses]

export type CreateWebhookGlWebhooksPostData = {
  body: GlWebhookCreate
  path?: never
  query?: never
  url: '/gl/webhooks'
}

export type CreateWebhookGlWebhooksPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateWebhookGlWebhooksPostError =
  CreateWebhookGlWebhooksPostErrors[keyof CreateWebhookGlWebhooksPostErrors]

export type CreateWebhookGlWebhooksPostResponses = {
  /**
   * Successful Response
   */
  201: GlWebhookRead
}

export type CreateWebhookGlWebhooksPostResponse =
  CreateWebhookGlWebhooksPostResponses[keyof CreateWebhookGlWebhooksPostResponses]

export type DeleteWebhookGlWebhooksWebhookIdDeleteData = {
  body?: never
  path: {
    /**
     * Webhook Id
     */
    webhook_id: string
  }
  query?: never
  url: '/gl/webhooks/{webhook_id}'
}

export type DeleteWebhookGlWebhooksWebhookIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteWebhookGlWebhooksWebhookIdDeleteError =
  DeleteWebhookGlWebhooksWebhookIdDeleteErrors[keyof DeleteWebhookGlWebhooksWebhookIdDeleteErrors]

export type DeleteWebhookGlWebhooksWebhookIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type DeleteWebhookGlWebhooksWebhookIdDeleteResponse =
  DeleteWebhookGlWebhooksWebhookIdDeleteResponses[keyof DeleteWebhookGlWebhooksWebhookIdDeleteResponses]

export type GetWebhookGlWebhooksWebhookIdGetData = {
  body?: never
  path: {
    /**
     * Webhook Id
     */
    webhook_id: string
  }
  query?: never
  url: '/gl/webhooks/{webhook_id}'
}

export type GetWebhookGlWebhooksWebhookIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetWebhookGlWebhooksWebhookIdGetError =
  GetWebhookGlWebhooksWebhookIdGetErrors[keyof GetWebhookGlWebhooksWebhookIdGetErrors]

export type GetWebhookGlWebhooksWebhookIdGetResponses = {
  /**
   * Successful Response
   */
  200: GlWebhookRead
}

export type GetWebhookGlWebhooksWebhookIdGetResponse =
  GetWebhookGlWebhooksWebhookIdGetResponses[keyof GetWebhookGlWebhooksWebhookIdGetResponses]

export type UpdateWebhookGlWebhooksWebhookIdPatchData = {
  body: GlWebhookUpdate
  path: {
    /**
     * Webhook Id
     */
    webhook_id: string
  }
  query?: never
  url: '/gl/webhooks/{webhook_id}'
}

export type UpdateWebhookGlWebhooksWebhookIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateWebhookGlWebhooksWebhookIdPatchError =
  UpdateWebhookGlWebhooksWebhookIdPatchErrors[keyof UpdateWebhookGlWebhooksWebhookIdPatchErrors]

export type UpdateWebhookGlWebhooksWebhookIdPatchResponses = {
  /**
   * Successful Response
   */
  200: GlWebhookRead
}

export type UpdateWebhookGlWebhooksWebhookIdPatchResponse =
  UpdateWebhookGlWebhooksWebhookIdPatchResponses[keyof UpdateWebhookGlWebhooksWebhookIdPatchResponses]

export type TriggerWebhookGlWebhooksWebhookIdTriggerPostData = {
  /**
   * Data
   */
  body: {
    [key: string]: unknown
  }
  headers: {
    /**
     * X-Gitlab-Token
     */
    'x-gitlab-token': string
    /**
     * X-Gitlab-Event
     */
    'x-gitlab-event': string
  }
  path: {
    /**
     * Webhook Id
     */
    webhook_id: string
  }
  query?: never
  url: '/gl/webhooks/{webhook_id}/trigger'
}

export type TriggerWebhookGlWebhooksWebhookIdTriggerPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type TriggerWebhookGlWebhooksWebhookIdTriggerPostError =
  TriggerWebhookGlWebhooksWebhookIdTriggerPostErrors[keyof TriggerWebhookGlWebhooksWebhookIdTriggerPostErrors]

export type TriggerWebhookGlWebhooksWebhookIdTriggerPostResponses = {
  /**
   * Successful Response
   */
  200: unknown
}
