// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ActionType
 *
 * Типы действий в системе.
 */
export type ActionType = 'create' | 'update' | 'delete' | 'assign' | 'unassign';

/**
 * ActorType
 *
 * Тип актора, совершившего действие.
 */
export type ActorType = 'web_user' | 'bot_user' | 'system';

/**
 * BotSettingsResponse
 *
 * Bot settings response schema.
 */
export type BotSettingsResponse = {
    /**
     * Key
     */
    key: string;
    /**
     * Value
     */
    value: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ChatResponse
 */
export type ChatResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title?: string | null;
};

/**
 * ChatUserChatResponse
 */
export type ChatUserChatResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type: string;
};

/**
 * ChatUserDetailResponse
 */
export type ChatUserDetailResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Roles
     */
    roles: Array<ChatUserRoleResponse>;
    /**
     * Chats
     */
    chats: Array<ChatUserChatResponse>;
};

/**
 * ChatUserResponse
 */
export type ChatUserResponse = {
    /**
     * Id
     */
    id: string;
};

/**
 * ChatUserRoleResponse
 */
export type ChatUserRoleResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * EntityType
 *
 * Типы сущностей в системе.
 */
export type EntityType = 'user' | 'chat_user' | 'role' | 'chat' | 'role_assignment' | 'chat_membership' | 'bot_settings';

/**
 * GlWebhookCreate
 *
 * Create GitLab Webhook schema.
 */
export type GlWebhookCreate = {
    /**
     * Name
     */
    name?: string;
    /**
     * Secret
     */
    secret: string;
    /**
     * Chat Id
     */
    chat_id: string;
};

/**
 * GlWebhookListResponse
 *
 * List response for webhooks.
 */
export type GlWebhookListResponse = {
    /**
     * Items
     */
    items: Array<GlWebhookRead>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * GlWebhookRead
 *
 * Read GitLab Webhook schema.
 */
export type GlWebhookRead = {
    /**
     * Name
     */
    name?: string;
    /**
     * Id
     */
    id: string;
    /**
     * Chat Id
     */
    chat_id: string;
    /**
     * Chat Title
     */
    chat_title?: string | null;
    /**
     * Created By Id
     */
    created_by_id: string;
    /**
     * Created By Name
     */
    created_by_name?: string | null;
    /**
     * Last Used At
     */
    last_used_at: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * GlWebhookUpdate
 *
 * Update GitLab Webhook schema.
 */
export type GlWebhookUpdate = {
    /**
     * Name
     */
    name?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LogEntryResponse
 *
 * Ответ с записью лога.
 */
export type LogEntryResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Timestamp
     */
    timestamp: string;
    actor_type: ActorType;
    /**
     * Actor Id
     */
    actor_id: string | null;
    action_type: ActionType;
    entity_type: EntityType;
    /**
     * Entity Id
     */
    entity_id: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Details
     */
    details: {
        [key: string]: unknown;
    } | null;
    /**
     * Web User Username
     */
    web_user_username: string | null;
    /**
     * Bot User Id
     */
    bot_user_id: string | null;
};

/**
 * PaginatedChatUsersResponse
 */
export type PaginatedChatUsersResponse = {
    /**
     * Items
     */
    items: Array<ChatUserResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PaginatedChatsResponse
 */
export type PaginatedChatsResponse = {
    /**
     * Items
     */
    items: Array<ChatResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PaginatedLogEntriesResponse
 *
 * Постраничный ответ с логами.
 */
export type PaginatedLogEntriesResponse = {
    /**
     * Items
     */
    items: Array<LogEntryResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PaginatedRolesResponse
 */
export type PaginatedRolesResponse = {
    /**
     * Items
     */
    items: Array<RoleResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * RoleCreate
 */
export type RoleCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * RoleResponse
 */
export type RoleResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
};

/**
 * RoleUpdate
 */
export type RoleUpdate = {
    /**
     * Name
     */
    name?: string | null;
};

/**
 * SendMessageRequest
 */
export type SendMessageRequest = {
    /**
     * Text
     *
     * Message text to send
     */
    text: string;
    /**
     * Parse Mode
     *
     * Parse mode for message formatting
     */
    parse_mode?: 'MarkdownV2' | 'HTML' | null;
};

/**
 * SendMessageResponse
 */
export type SendMessageResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Message
     */
    message: string;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * TokenLoginRequest
 */
export type TokenLoginRequest = {
    /**
     * Token
     */
    token: string;
};

/**
 * UpdateBotSettingsRequest
 *
 * Update bot settings request schema.
 */
export type UpdateBotSettingsRequest = {
    /**
     * Value
     */
    value: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type LoginApiAuthLoginPostData = {
    body: TokenLoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginApiAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiAuthLoginPostError = LoginApiAuthLoginPostErrors[keyof LoginApiAuthLoginPostErrors];

export type LoginApiAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginApiAuthLoginPostResponse = LoginApiAuthLoginPostResponses[keyof LoginApiAuthLoginPostResponses];

export type GetCurrentUserInfoApiAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetCurrentUserInfoApiAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetCurrentUserInfoApiAuthMeGetResponse = GetCurrentUserInfoApiAuthMeGetResponses[keyof GetCurrentUserInfoApiAuthMeGetResponses];

export type ListChatsApiChatsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
    };
    url: '/api/chats';
};

export type ListChatsApiChatsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListChatsApiChatsGetError = ListChatsApiChatsGetErrors[keyof ListChatsApiChatsGetErrors];

export type ListChatsApiChatsGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedChatsResponse;
};

export type ListChatsApiChatsGetResponse = ListChatsApiChatsGetResponses[keyof ListChatsApiChatsGetResponses];

export type GetChatApiChatsChatIdGetData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/api/chats/{chat_id}';
};

export type GetChatApiChatsChatIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChatApiChatsChatIdGetError = GetChatApiChatsChatIdGetErrors[keyof GetChatApiChatsChatIdGetErrors];

export type GetChatApiChatsChatIdGetResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type GetChatApiChatsChatIdGetResponse = GetChatApiChatsChatIdGetResponses[keyof GetChatApiChatsChatIdGetResponses];

export type SendMessageApiChatsChatIdSendMessagePostData = {
    body: SendMessageRequest;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/api/chats/{chat_id}/send-message';
};

export type SendMessageApiChatsChatIdSendMessagePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendMessageApiChatsChatIdSendMessagePostError = SendMessageApiChatsChatIdSendMessagePostErrors[keyof SendMessageApiChatsChatIdSendMessagePostErrors];

export type SendMessageApiChatsChatIdSendMessagePostResponses = {
    /**
     * Successful Response
     */
    200: SendMessageResponse;
};

export type SendMessageApiChatsChatIdSendMessagePostResponse = SendMessageApiChatsChatIdSendMessagePostResponses[keyof SendMessageApiChatsChatIdSendMessagePostResponses];

export type ListRolesApiRolesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
    };
    url: '/api/roles';
};

export type ListRolesApiRolesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRolesApiRolesGetError = ListRolesApiRolesGetErrors[keyof ListRolesApiRolesGetErrors];

export type ListRolesApiRolesGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedRolesResponse;
};

export type ListRolesApiRolesGetResponse = ListRolesApiRolesGetResponses[keyof ListRolesApiRolesGetResponses];

export type CreateRoleApiRolesPostData = {
    body: RoleCreate;
    path?: never;
    query?: never;
    url: '/api/roles';
};

export type CreateRoleApiRolesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRoleApiRolesPostError = CreateRoleApiRolesPostErrors[keyof CreateRoleApiRolesPostErrors];

export type CreateRoleApiRolesPostResponses = {
    /**
     * Successful Response
     */
    201: RoleResponse;
};

export type CreateRoleApiRolesPostResponse = CreateRoleApiRolesPostResponses[keyof CreateRoleApiRolesPostResponses];

export type DeleteRoleApiRolesRoleIdDeleteData = {
    body?: never;
    path: {
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/roles/{role_id}';
};

export type DeleteRoleApiRolesRoleIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRoleApiRolesRoleIdDeleteError = DeleteRoleApiRolesRoleIdDeleteErrors[keyof DeleteRoleApiRolesRoleIdDeleteErrors];

export type DeleteRoleApiRolesRoleIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteRoleApiRolesRoleIdDeleteResponse = DeleteRoleApiRolesRoleIdDeleteResponses[keyof DeleteRoleApiRolesRoleIdDeleteResponses];

export type UpdateRoleApiRolesRoleIdPatchData = {
    body: RoleUpdate;
    path: {
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/roles/{role_id}';
};

export type UpdateRoleApiRolesRoleIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateRoleApiRolesRoleIdPatchError = UpdateRoleApiRolesRoleIdPatchErrors[keyof UpdateRoleApiRolesRoleIdPatchErrors];

export type UpdateRoleApiRolesRoleIdPatchResponses = {
    /**
     * Successful Response
     */
    200: RoleResponse;
};

export type UpdateRoleApiRolesRoleIdPatchResponse = UpdateRoleApiRolesRoleIdPatchResponses[keyof UpdateRoleApiRolesRoleIdPatchResponses];

export type ListChatUsersApiChatUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
    };
    url: '/api/chat-users';
};

export type ListChatUsersApiChatUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListChatUsersApiChatUsersGetError = ListChatUsersApiChatUsersGetErrors[keyof ListChatUsersApiChatUsersGetErrors];

export type ListChatUsersApiChatUsersGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedChatUsersResponse;
};

export type ListChatUsersApiChatUsersGetResponse = ListChatUsersApiChatUsersGetResponses[keyof ListChatUsersApiChatUsersGetResponses];

export type GetChatUserApiChatUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/chat-users/{user_id}';
};

export type GetChatUserApiChatUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChatUserApiChatUsersUserIdGetError = GetChatUserApiChatUsersUserIdGetErrors[keyof GetChatUserApiChatUsersUserIdGetErrors];

export type GetChatUserApiChatUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: ChatUserDetailResponse;
};

export type GetChatUserApiChatUsersUserIdGetResponse = GetChatUserApiChatUsersUserIdGetResponses[keyof GetChatUserApiChatUsersUserIdGetResponses];

export type RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/chat-users/{user_id}/roles/{role_id}';
};

export type RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteError = RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteErrors[keyof RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteErrors];

export type RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteResponse = RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteResponses[keyof RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteResponses];

export type AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/chat-users/{user_id}/roles/{role_id}';
};

export type AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostError = AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostErrors[keyof AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostErrors];

export type AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostResponses = {
    /**
     * Response Assign Role To User Api Chat Users  User Id  Roles  Role Id  Post
     *
     * Successful Response
     */
    201: {
        [key: string]: string;
    };
};

export type AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostResponse = AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostResponses[keyof AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostResponses];

export type GetBotSettingApiBotSettingsKeyGetData = {
    body?: never;
    path: {
        /**
         * Key
         */
        key: string;
    };
    query?: never;
    url: '/api/bot-settings/{key}';
};

export type GetBotSettingApiBotSettingsKeyGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBotSettingApiBotSettingsKeyGetError = GetBotSettingApiBotSettingsKeyGetErrors[keyof GetBotSettingApiBotSettingsKeyGetErrors];

export type GetBotSettingApiBotSettingsKeyGetResponses = {
    /**
     * Successful Response
     */
    200: BotSettingsResponse;
};

export type GetBotSettingApiBotSettingsKeyGetResponse = GetBotSettingApiBotSettingsKeyGetResponses[keyof GetBotSettingApiBotSettingsKeyGetResponses];

export type UpdateBotSettingApiBotSettingsKeyPutData = {
    body: UpdateBotSettingsRequest;
    path: {
        /**
         * Key
         */
        key: string;
    };
    query?: never;
    url: '/api/bot-settings/{key}';
};

export type UpdateBotSettingApiBotSettingsKeyPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateBotSettingApiBotSettingsKeyPutError = UpdateBotSettingApiBotSettingsKeyPutErrors[keyof UpdateBotSettingApiBotSettingsKeyPutErrors];

export type UpdateBotSettingApiBotSettingsKeyPutResponses = {
    /**
     * Successful Response
     */
    200: BotSettingsResponse;
};

export type UpdateBotSettingApiBotSettingsKeyPutResponse = UpdateBotSettingApiBotSettingsKeyPutResponses[keyof UpdateBotSettingApiBotSettingsKeyPutResponses];

export type ListBotSettingsApiBotSettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/bot-settings';
};

export type ListBotSettingsApiBotSettingsGetResponses = {
    /**
     * Response List Bot Settings Api Bot Settings Get
     *
     * Successful Response
     */
    200: Array<BotSettingsResponse>;
};

export type ListBotSettingsApiBotSettingsGetResponse = ListBotSettingsApiBotSettingsGetResponses[keyof ListBotSettingsApiBotSettingsGetResponses];

export type ListLogsApiLogsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
        /**
         * Actor Type
         */
        actor_type?: ActorType | null;
        /**
         * Actor Id
         */
        actor_id?: string | null;
        /**
         * Action Type
         */
        action_type?: ActionType | null;
        /**
         * Entity Type
         */
        entity_type?: EntityType | null;
        /**
         * Entity Id
         */
        entity_id?: string | null;
        /**
         * Start Date
         */
        start_date?: string | null;
        /**
         * End Date
         */
        end_date?: string | null;
        /**
         * Search Query
         */
        search_query?: string | null;
    };
    url: '/api/logs';
};

export type ListLogsApiLogsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListLogsApiLogsGetError = ListLogsApiLogsGetErrors[keyof ListLogsApiLogsGetErrors];

export type ListLogsApiLogsGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedLogEntriesResponse;
};

export type ListLogsApiLogsGetResponse = ListLogsApiLogsGetResponses[keyof ListLogsApiLogsGetResponses];

export type GetLogApiLogsLogIdGetData = {
    body?: never;
    path: {
        /**
         * Log Id
         */
        log_id: number;
    };
    query?: never;
    url: '/api/logs/{log_id}';
};

export type GetLogApiLogsLogIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLogApiLogsLogIdGetError = GetLogApiLogsLogIdGetErrors[keyof GetLogApiLogsLogIdGetErrors];

export type GetLogApiLogsLogIdGetResponses = {
    /**
     * Successful Response
     */
    200: LogEntryResponse;
};

export type GetLogApiLogsLogIdGetResponse = GetLogApiLogsLogIdGetResponses[keyof GetLogApiLogsLogIdGetResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListWebhooksGlWebhooksGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
    };
    url: '/gl/webhooks';
};

export type ListWebhooksGlWebhooksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListWebhooksGlWebhooksGetError = ListWebhooksGlWebhooksGetErrors[keyof ListWebhooksGlWebhooksGetErrors];

export type ListWebhooksGlWebhooksGetResponses = {
    /**
     * Successful Response
     */
    200: GlWebhookListResponse;
};

export type ListWebhooksGlWebhooksGetResponse = ListWebhooksGlWebhooksGetResponses[keyof ListWebhooksGlWebhooksGetResponses];

export type CreateWebhookGlWebhooksPostData = {
    body: GlWebhookCreate;
    path?: never;
    query?: never;
    url: '/gl/webhooks';
};

export type CreateWebhookGlWebhooksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateWebhookGlWebhooksPostError = CreateWebhookGlWebhooksPostErrors[keyof CreateWebhookGlWebhooksPostErrors];

export type CreateWebhookGlWebhooksPostResponses = {
    /**
     * Successful Response
     */
    201: GlWebhookRead;
};

export type CreateWebhookGlWebhooksPostResponse = CreateWebhookGlWebhooksPostResponses[keyof CreateWebhookGlWebhooksPostResponses];

export type DeleteWebhookGlWebhooksWebhookIdDeleteData = {
    body?: never;
    path: {
        /**
         * Webhook Id
         */
        webhook_id: string;
    };
    query?: never;
    url: '/gl/webhooks/{webhook_id}';
};

export type DeleteWebhookGlWebhooksWebhookIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteWebhookGlWebhooksWebhookIdDeleteError = DeleteWebhookGlWebhooksWebhookIdDeleteErrors[keyof DeleteWebhookGlWebhooksWebhookIdDeleteErrors];

export type DeleteWebhookGlWebhooksWebhookIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteWebhookGlWebhooksWebhookIdDeleteResponse = DeleteWebhookGlWebhooksWebhookIdDeleteResponses[keyof DeleteWebhookGlWebhooksWebhookIdDeleteResponses];

export type GetWebhookGlWebhooksWebhookIdGetData = {
    body?: never;
    path: {
        /**
         * Webhook Id
         */
        webhook_id: string;
    };
    query?: never;
    url: '/gl/webhooks/{webhook_id}';
};

export type GetWebhookGlWebhooksWebhookIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWebhookGlWebhooksWebhookIdGetError = GetWebhookGlWebhooksWebhookIdGetErrors[keyof GetWebhookGlWebhooksWebhookIdGetErrors];

export type GetWebhookGlWebhooksWebhookIdGetResponses = {
    /**
     * Successful Response
     */
    200: GlWebhookRead;
};

export type GetWebhookGlWebhooksWebhookIdGetResponse = GetWebhookGlWebhooksWebhookIdGetResponses[keyof GetWebhookGlWebhooksWebhookIdGetResponses];

export type UpdateWebhookGlWebhooksWebhookIdPatchData = {
    body: GlWebhookUpdate;
    path: {
        /**
         * Webhook Id
         */
        webhook_id: string;
    };
    query?: never;
    url: '/gl/webhooks/{webhook_id}';
};

export type UpdateWebhookGlWebhooksWebhookIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateWebhookGlWebhooksWebhookIdPatchError = UpdateWebhookGlWebhooksWebhookIdPatchErrors[keyof UpdateWebhookGlWebhooksWebhookIdPatchErrors];

export type UpdateWebhookGlWebhooksWebhookIdPatchResponses = {
    /**
     * Successful Response
     */
    200: GlWebhookRead;
};

export type UpdateWebhookGlWebhooksWebhookIdPatchResponse = UpdateWebhookGlWebhooksWebhookIdPatchResponses[keyof UpdateWebhookGlWebhooksWebhookIdPatchResponses];

export type TriggerWebhookGlWebhooksWebhookIdTriggerPostData = {
    /**
     * Data
     */
    body: {
        [key: string]: unknown;
    };
    headers: {
        /**
         * X-Gitlab-Token
         */
        'x-gitlab-token': string;
        /**
         * X-Gitlab-Event
         */
        'x-gitlab-event': string;
    };
    path: {
        /**
         * Webhook Id
         */
        webhook_id: string;
    };
    query?: never;
    url: '/gl/webhooks/{webhook_id}/trigger';
};

export type TriggerWebhookGlWebhooksWebhookIdTriggerPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerWebhookGlWebhooksWebhookIdTriggerPostError = TriggerWebhookGlWebhooksWebhookIdTriggerPostErrors[keyof TriggerWebhookGlWebhooksWebhookIdTriggerPostErrors];

export type TriggerWebhookGlWebhooksWebhookIdTriggerPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
