// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from '@tanstack/vue-query'

import { client } from '../client.gen'
import {
  addRoleMemberApiRolesRoleIdMembersPost,
  assignRoleToUserApiChatUsersUserIdRolesRoleIdPost,
  createRoleApiRolesPost,
  createWebhookApiWebhooksPost,
  createWebhookGlWebhooksPost,
  deleteRoleApiRolesRoleIdDelete,
  deleteWebhookApiWebhooksWebhookIdDelete,
  deleteWebhookGlWebhooksWebhookIdDelete,
  getBotSettingApiBotSettingsKeyGet,
  getChatApiChatsChatIdGet,
  getChatUserApiChatUsersUserIdGet,
  getCurrentUserInfoApiAuthMeGet,
  getEventApiEventsEventIdGet,
  getOverviewApiOverviewGet,
  getRoleApiRolesRoleIdGet,
  getSessionApiAiSessionsSessionIdGet,
  getStatusApiAiStatusGet,
  getUsageApiAiUsageGet,
  getWebhookApiWebhooksWebhookIdGet,
  getWebhookGlWebhooksWebhookIdGet,
  handleWebhookWebhooksWebhookIdPost,
  healthHealthGet,
  listBotSettingsApiBotSettingsGet,
  listChatEventsApiChatsChatIdEventsGet,
  listChatsApiChatsGet,
  listChatUsersApiChatUsersGet,
  listChatWebhooksApiChatsChatIdWebhooksGet,
  listEventsApiEventsGet,
  listEventTypesApiEventsTypesGet,
  listRolesApiRolesGet,
  listSessionsApiAiSessionsGet,
  listWebhooksApiWebhooksGet,
  listWebhooksGlWebhooksGet,
  loginApiAuthLoginPost,
  type Options,
  regenerateWebhookApiKeyApiWebhooksWebhookIdRegeneratePost,
  removeRoleFromUserApiChatUsersUserIdRolesRoleIdDelete,
  removeRoleMemberApiRolesRoleIdMembersUserIdDelete,
  rootGet,
  sendMessageApiChatsChatIdSendMessagePost,
  triggerWebhookGlWebhooksWebhookIdTriggerPost,
  updateBotSettingApiBotSettingsKeyPut,
  updateChatUserApiChatUsersUserIdPatch,
  updateRoleApiRolesRoleIdPatch,
  updateWebhookApiWebhooksWebhookIdPut,
  updateWebhookGlWebhooksWebhookIdPatch,
} from '../sdk.gen'
import type {
  AddRoleMemberApiRolesRoleIdMembersPostData,
  AddRoleMemberApiRolesRoleIdMembersPostError,
  AddRoleMemberApiRolesRoleIdMembersPostResponse,
  AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostData,
  AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostError,
  AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostResponse,
  CreateRoleApiRolesPostData,
  CreateRoleApiRolesPostError,
  CreateRoleApiRolesPostResponse,
  CreateWebhookApiWebhooksPostData,
  CreateWebhookApiWebhooksPostError,
  CreateWebhookApiWebhooksPostResponse,
  CreateWebhookGlWebhooksPostData,
  CreateWebhookGlWebhooksPostError,
  CreateWebhookGlWebhooksPostResponse,
  DeleteRoleApiRolesRoleIdDeleteData,
  DeleteRoleApiRolesRoleIdDeleteError,
  DeleteRoleApiRolesRoleIdDeleteResponse,
  DeleteWebhookApiWebhooksWebhookIdDeleteData,
  DeleteWebhookApiWebhooksWebhookIdDeleteError,
  DeleteWebhookApiWebhooksWebhookIdDeleteResponse,
  DeleteWebhookGlWebhooksWebhookIdDeleteData,
  DeleteWebhookGlWebhooksWebhookIdDeleteError,
  DeleteWebhookGlWebhooksWebhookIdDeleteResponse,
  GetBotSettingApiBotSettingsKeyGetData,
  GetBotSettingApiBotSettingsKeyGetError,
  GetBotSettingApiBotSettingsKeyGetResponse,
  GetChatApiChatsChatIdGetData,
  GetChatApiChatsChatIdGetError,
  GetChatApiChatsChatIdGetResponse,
  GetChatUserApiChatUsersUserIdGetData,
  GetChatUserApiChatUsersUserIdGetError,
  GetChatUserApiChatUsersUserIdGetResponse,
  GetCurrentUserInfoApiAuthMeGetData,
  GetCurrentUserInfoApiAuthMeGetResponse,
  GetEventApiEventsEventIdGetData,
  GetEventApiEventsEventIdGetError,
  GetEventApiEventsEventIdGetResponse,
  GetOverviewApiOverviewGetData,
  GetOverviewApiOverviewGetError,
  GetOverviewApiOverviewGetResponse,
  GetRoleApiRolesRoleIdGetData,
  GetRoleApiRolesRoleIdGetError,
  GetRoleApiRolesRoleIdGetResponse,
  GetSessionApiAiSessionsSessionIdGetData,
  GetSessionApiAiSessionsSessionIdGetError,
  GetSessionApiAiSessionsSessionIdGetResponse,
  GetStatusApiAiStatusGetData,
  GetStatusApiAiStatusGetResponse,
  GetUsageApiAiUsageGetData,
  GetUsageApiAiUsageGetError,
  GetUsageApiAiUsageGetResponse,
  GetWebhookApiWebhooksWebhookIdGetData,
  GetWebhookApiWebhooksWebhookIdGetError,
  GetWebhookApiWebhooksWebhookIdGetResponse,
  GetWebhookGlWebhooksWebhookIdGetData,
  GetWebhookGlWebhooksWebhookIdGetError,
  GetWebhookGlWebhooksWebhookIdGetResponse,
  HandleWebhookWebhooksWebhookIdPostData,
  HandleWebhookWebhooksWebhookIdPostError,
  HandleWebhookWebhooksWebhookIdPostResponse,
  HealthHealthGetData,
  ListBotSettingsApiBotSettingsGetData,
  ListBotSettingsApiBotSettingsGetResponse,
  ListChatEventsApiChatsChatIdEventsGetData,
  ListChatEventsApiChatsChatIdEventsGetError,
  ListChatEventsApiChatsChatIdEventsGetResponse,
  ListChatsApiChatsGetData,
  ListChatsApiChatsGetError,
  ListChatsApiChatsGetResponse,
  ListChatUsersApiChatUsersGetData,
  ListChatUsersApiChatUsersGetError,
  ListChatUsersApiChatUsersGetResponse,
  ListChatWebhooksApiChatsChatIdWebhooksGetData,
  ListChatWebhooksApiChatsChatIdWebhooksGetError,
  ListChatWebhooksApiChatsChatIdWebhooksGetResponse,
  ListEventsApiEventsGetData,
  ListEventsApiEventsGetError,
  ListEventsApiEventsGetResponse,
  ListEventTypesApiEventsTypesGetData,
  ListEventTypesApiEventsTypesGetResponse,
  ListRolesApiRolesGetData,
  ListRolesApiRolesGetError,
  ListRolesApiRolesGetResponse,
  ListSessionsApiAiSessionsGetData,
  ListSessionsApiAiSessionsGetError,
  ListSessionsApiAiSessionsGetResponse,
  ListWebhooksApiWebhooksGetData,
  ListWebhooksApiWebhooksGetResponse,
  ListWebhooksGlWebhooksGetData,
  ListWebhooksGlWebhooksGetError,
  ListWebhooksGlWebhooksGetResponse,
  LoginApiAuthLoginPostData,
  LoginApiAuthLoginPostError,
  LoginApiAuthLoginPostResponse,
  RegenerateWebhookApiKeyApiWebhooksWebhookIdRegeneratePostData,
  RegenerateWebhookApiKeyApiWebhooksWebhookIdRegeneratePostError,
  RegenerateWebhookApiKeyApiWebhooksWebhookIdRegeneratePostResponse,
  RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteData,
  RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteError,
  RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteResponse,
  RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteData,
  RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteError,
  RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteResponse,
  RootGetData,
  SendMessageApiChatsChatIdSendMessagePostData,
  SendMessageApiChatsChatIdSendMessagePostError,
  SendMessageApiChatsChatIdSendMessagePostResponse,
  TriggerWebhookGlWebhooksWebhookIdTriggerPostData,
  TriggerWebhookGlWebhooksWebhookIdTriggerPostError,
  UpdateBotSettingApiBotSettingsKeyPutData,
  UpdateBotSettingApiBotSettingsKeyPutError,
  UpdateBotSettingApiBotSettingsKeyPutResponse,
  UpdateChatUserApiChatUsersUserIdPatchData,
  UpdateChatUserApiChatUsersUserIdPatchError,
  UpdateChatUserApiChatUsersUserIdPatchResponse,
  UpdateRoleApiRolesRoleIdPatchData,
  UpdateRoleApiRolesRoleIdPatchError,
  UpdateRoleApiRolesRoleIdPatchResponse,
  UpdateWebhookApiWebhooksWebhookIdPutData,
  UpdateWebhookApiWebhooksWebhookIdPutError,
  UpdateWebhookApiWebhooksWebhookIdPutResponse,
  UpdateWebhookGlWebhooksWebhookIdPatchData,
  UpdateWebhookGlWebhooksWebhookIdPatchError,
  UpdateWebhookGlWebhooksWebhookIdPatchResponse,
} from '../types.gen'

/**
 * Login
 *
 * Login with temporary token from bot.
 */
export const loginApiAuthLoginPostMutation = (
  options?: Partial<Options<LoginApiAuthLoginPostData>>,
): UseMutationOptions<
  LoginApiAuthLoginPostResponse,
  LoginApiAuthLoginPostError,
  Options<LoginApiAuthLoginPostData>
> => {
  const mutationOptions: UseMutationOptions<
    LoginApiAuthLoginPostResponse,
    LoginApiAuthLoginPostError,
    Options<LoginApiAuthLoginPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await loginApiAuthLoginPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const getCurrentUserInfoApiAuthMeGetQueryKey = (
  options?: Options<GetCurrentUserInfoApiAuthMeGetData>,
) => createQueryKey('getCurrentUserInfoApiAuthMeGet', options)

/**
 * Get Current User Info
 *
 * Get current authenticated user information.
 */
export const getCurrentUserInfoApiAuthMeGetOptions = (
  options?: Options<GetCurrentUserInfoApiAuthMeGetData>,
) =>
  queryOptions<
    GetCurrentUserInfoApiAuthMeGetResponse,
    DefaultError,
    GetCurrentUserInfoApiAuthMeGetResponse,
    ReturnType<typeof getCurrentUserInfoApiAuthMeGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCurrentUserInfoApiAuthMeGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getCurrentUserInfoApiAuthMeGetQueryKey(options),
  })

export const listChatsApiChatsGetQueryKey = (options?: Options<ListChatsApiChatsGetData>) =>
  createQueryKey('listChatsApiChatsGet', options)

/**
 * List Chats
 *
 * List all chats with pagination. Optional search by title or id.
 */
export const listChatsApiChatsGetOptions = (options?: Options<ListChatsApiChatsGetData>) =>
  queryOptions<
    ListChatsApiChatsGetResponse,
    ListChatsApiChatsGetError,
    ListChatsApiChatsGetResponse,
    ReturnType<typeof listChatsApiChatsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listChatsApiChatsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listChatsApiChatsGetQueryKey(options),
  })

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    }
  }
  return params as unknown as typeof page
}

export const listChatsApiChatsGetInfiniteQueryKey = (
  options?: Options<ListChatsApiChatsGetData>,
): QueryKey<Options<ListChatsApiChatsGetData>> =>
  createQueryKey('listChatsApiChatsGet', options, true)

/**
 * List Chats
 *
 * List all chats with pagination. Optional search by title or id.
 */
export const listChatsApiChatsGetInfiniteOptions = (options?: Options<ListChatsApiChatsGetData>) =>
  infiniteQueryOptions<
    ListChatsApiChatsGetResponse,
    ListChatsApiChatsGetError,
    InfiniteData<ListChatsApiChatsGetResponse>,
    QueryKey<Options<ListChatsApiChatsGetData>>,
    | number
    | Pick<QueryKey<Options<ListChatsApiChatsGetData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListChatsApiChatsGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await listChatsApiChatsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: listChatsApiChatsGetInfiniteQueryKey(options),
    },
  )

export const getChatApiChatsChatIdGetQueryKey = (options: Options<GetChatApiChatsChatIdGetData>) =>
  createQueryKey('getChatApiChatsChatIdGet', options)

/**
 * Get Chat
 *
 * Get chat by ID with member and webhook counts.
 */
export const getChatApiChatsChatIdGetOptions = (options: Options<GetChatApiChatsChatIdGetData>) =>
  queryOptions<
    GetChatApiChatsChatIdGetResponse,
    GetChatApiChatsChatIdGetError,
    GetChatApiChatsChatIdGetResponse,
    ReturnType<typeof getChatApiChatsChatIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getChatApiChatsChatIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getChatApiChatsChatIdGetQueryKey(options),
  })

export const listChatWebhooksApiChatsChatIdWebhooksGetQueryKey = (
  options: Options<ListChatWebhooksApiChatsChatIdWebhooksGetData>,
) => createQueryKey('listChatWebhooksApiChatsChatIdWebhooksGet', options)

/**
 * List Chat Webhooks
 *
 * Вебхуки, отправляющие в этот чат.
 */
export const listChatWebhooksApiChatsChatIdWebhooksGetOptions = (
  options: Options<ListChatWebhooksApiChatsChatIdWebhooksGetData>,
) =>
  queryOptions<
    ListChatWebhooksApiChatsChatIdWebhooksGetResponse,
    ListChatWebhooksApiChatsChatIdWebhooksGetError,
    ListChatWebhooksApiChatsChatIdWebhooksGetResponse,
    ReturnType<typeof listChatWebhooksApiChatsChatIdWebhooksGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listChatWebhooksApiChatsChatIdWebhooksGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listChatWebhooksApiChatsChatIdWebhooksGetQueryKey(options),
  })

export const listChatEventsApiChatsChatIdEventsGetQueryKey = (
  options: Options<ListChatEventsApiChatsChatIdEventsGetData>,
) => createQueryKey('listChatEventsApiChatsChatIdEventsGet', options)

/**
 * List Chat Events
 *
 * Лента событий чата.
 *
 * Админ видит всё, участник — то же, но без текстов сообщений.
 * Посторонний не видит ничего: ответ такой же, как для несуществующего
 * чата, иначе по кодам ответа можно перебирать чужие чаты.
 */
export const listChatEventsApiChatsChatIdEventsGetOptions = (
  options: Options<ListChatEventsApiChatsChatIdEventsGetData>,
) =>
  queryOptions<
    ListChatEventsApiChatsChatIdEventsGetResponse,
    ListChatEventsApiChatsChatIdEventsGetError,
    ListChatEventsApiChatsChatIdEventsGetResponse,
    ReturnType<typeof listChatEventsApiChatsChatIdEventsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listChatEventsApiChatsChatIdEventsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listChatEventsApiChatsChatIdEventsGetQueryKey(options),
  })

export const listChatEventsApiChatsChatIdEventsGetInfiniteQueryKey = (
  options: Options<ListChatEventsApiChatsChatIdEventsGetData>,
): QueryKey<Options<ListChatEventsApiChatsChatIdEventsGetData>> =>
  createQueryKey('listChatEventsApiChatsChatIdEventsGet', options, true)

/**
 * List Chat Events
 *
 * Лента событий чата.
 *
 * Админ видит всё, участник — то же, но без текстов сообщений.
 * Посторонний не видит ничего: ответ такой же, как для несуществующего
 * чата, иначе по кодам ответа можно перебирать чужие чаты.
 */
export const listChatEventsApiChatsChatIdEventsGetInfiniteOptions = (
  options: Options<ListChatEventsApiChatsChatIdEventsGetData>,
) =>
  infiniteQueryOptions<
    ListChatEventsApiChatsChatIdEventsGetResponse,
    ListChatEventsApiChatsChatIdEventsGetError,
    InfiniteData<ListChatEventsApiChatsChatIdEventsGetResponse>,
    QueryKey<Options<ListChatEventsApiChatsChatIdEventsGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListChatEventsApiChatsChatIdEventsGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListChatEventsApiChatsChatIdEventsGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await listChatEventsApiChatsChatIdEventsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: listChatEventsApiChatsChatIdEventsGetInfiniteQueryKey(options),
    },
  )

/**
 * Send Message
 *
 * Send a message to a chat. Admin only.
 */
export const sendMessageApiChatsChatIdSendMessagePostMutation = (
  options?: Partial<Options<SendMessageApiChatsChatIdSendMessagePostData>>,
): UseMutationOptions<
  SendMessageApiChatsChatIdSendMessagePostResponse,
  SendMessageApiChatsChatIdSendMessagePostError,
  Options<SendMessageApiChatsChatIdSendMessagePostData>
> => {
  const mutationOptions: UseMutationOptions<
    SendMessageApiChatsChatIdSendMessagePostResponse,
    SendMessageApiChatsChatIdSendMessagePostError,
    Options<SendMessageApiChatsChatIdSendMessagePostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await sendMessageApiChatsChatIdSendMessagePost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listRolesApiRolesGetQueryKey = (options?: Options<ListRolesApiRolesGetData>) =>
  createQueryKey('listRolesApiRolesGet', options)

/**
 * List Roles
 *
 * List all roles with pagination.
 */
export const listRolesApiRolesGetOptions = (options?: Options<ListRolesApiRolesGetData>) =>
  queryOptions<
    ListRolesApiRolesGetResponse,
    ListRolesApiRolesGetError,
    ListRolesApiRolesGetResponse,
    ReturnType<typeof listRolesApiRolesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listRolesApiRolesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listRolesApiRolesGetQueryKey(options),
  })

export const listRolesApiRolesGetInfiniteQueryKey = (
  options?: Options<ListRolesApiRolesGetData>,
): QueryKey<Options<ListRolesApiRolesGetData>> =>
  createQueryKey('listRolesApiRolesGet', options, true)

/**
 * List Roles
 *
 * List all roles with pagination.
 */
export const listRolesApiRolesGetInfiniteOptions = (options?: Options<ListRolesApiRolesGetData>) =>
  infiniteQueryOptions<
    ListRolesApiRolesGetResponse,
    ListRolesApiRolesGetError,
    InfiniteData<ListRolesApiRolesGetResponse>,
    QueryKey<Options<ListRolesApiRolesGetData>>,
    | number
    | Pick<QueryKey<Options<ListRolesApiRolesGetData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListRolesApiRolesGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await listRolesApiRolesGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: listRolesApiRolesGetInfiniteQueryKey(options),
    },
  )

/**
 * Create Role
 *
 * Create new role. Admin only.
 */
export const createRoleApiRolesPostMutation = (
  options?: Partial<Options<CreateRoleApiRolesPostData>>,
): UseMutationOptions<
  CreateRoleApiRolesPostResponse,
  CreateRoleApiRolesPostError,
  Options<CreateRoleApiRolesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateRoleApiRolesPostResponse,
    CreateRoleApiRolesPostError,
    Options<CreateRoleApiRolesPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createRoleApiRolesPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete Role
 *
 * Delete role. Admin only.
 */
export const deleteRoleApiRolesRoleIdDeleteMutation = (
  options?: Partial<Options<DeleteRoleApiRolesRoleIdDeleteData>>,
): UseMutationOptions<
  DeleteRoleApiRolesRoleIdDeleteResponse,
  DeleteRoleApiRolesRoleIdDeleteError,
  Options<DeleteRoleApiRolesRoleIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteRoleApiRolesRoleIdDeleteResponse,
    DeleteRoleApiRolesRoleIdDeleteError,
    Options<DeleteRoleApiRolesRoleIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteRoleApiRolesRoleIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getRoleApiRolesRoleIdGetQueryKey = (options: Options<GetRoleApiRolesRoleIdGetData>) =>
  createQueryKey('getRoleApiRolesRoleIdGet', options)

/**
 * Get Role
 *
 * Get role by ID with its members.
 */
export const getRoleApiRolesRoleIdGetOptions = (options: Options<GetRoleApiRolesRoleIdGetData>) =>
  queryOptions<
    GetRoleApiRolesRoleIdGetResponse,
    GetRoleApiRolesRoleIdGetError,
    GetRoleApiRolesRoleIdGetResponse,
    ReturnType<typeof getRoleApiRolesRoleIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRoleApiRolesRoleIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getRoleApiRolesRoleIdGetQueryKey(options),
  })

/**
 * Update Role
 *
 * Update role. Admin only.
 */
export const updateRoleApiRolesRoleIdPatchMutation = (
  options?: Partial<Options<UpdateRoleApiRolesRoleIdPatchData>>,
): UseMutationOptions<
  UpdateRoleApiRolesRoleIdPatchResponse,
  UpdateRoleApiRolesRoleIdPatchError,
  Options<UpdateRoleApiRolesRoleIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateRoleApiRolesRoleIdPatchResponse,
    UpdateRoleApiRolesRoleIdPatchError,
    Options<UpdateRoleApiRolesRoleIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateRoleApiRolesRoleIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Add Role Member
 *
 * Add member to role. Admin only.
 */
export const addRoleMemberApiRolesRoleIdMembersPostMutation = (
  options?: Partial<Options<AddRoleMemberApiRolesRoleIdMembersPostData>>,
): UseMutationOptions<
  AddRoleMemberApiRolesRoleIdMembersPostResponse,
  AddRoleMemberApiRolesRoleIdMembersPostError,
  Options<AddRoleMemberApiRolesRoleIdMembersPostData>
> => {
  const mutationOptions: UseMutationOptions<
    AddRoleMemberApiRolesRoleIdMembersPostResponse,
    AddRoleMemberApiRolesRoleIdMembersPostError,
    Options<AddRoleMemberApiRolesRoleIdMembersPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await addRoleMemberApiRolesRoleIdMembersPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Remove Role Member
 *
 * Remove member from role. Admin only.
 */
export const removeRoleMemberApiRolesRoleIdMembersUserIdDeleteMutation = (
  options?: Partial<Options<RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteData>>,
): UseMutationOptions<
  RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteResponse,
  RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteError,
  Options<RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteResponse,
    RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteError,
    Options<RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await removeRoleMemberApiRolesRoleIdMembersUserIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listChatUsersApiChatUsersGetQueryKey = (
  options?: Options<ListChatUsersApiChatUsersGetData>,
) => createQueryKey('listChatUsersApiChatUsersGet', options)

/**
 * List Chat Users
 *
 * List all chat users with pagination.
 *
 * Optional search by name or id and filter by chat membership.
 */
export const listChatUsersApiChatUsersGetOptions = (
  options?: Options<ListChatUsersApiChatUsersGetData>,
) =>
  queryOptions<
    ListChatUsersApiChatUsersGetResponse,
    ListChatUsersApiChatUsersGetError,
    ListChatUsersApiChatUsersGetResponse,
    ReturnType<typeof listChatUsersApiChatUsersGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listChatUsersApiChatUsersGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listChatUsersApiChatUsersGetQueryKey(options),
  })

export const listChatUsersApiChatUsersGetInfiniteQueryKey = (
  options?: Options<ListChatUsersApiChatUsersGetData>,
): QueryKey<Options<ListChatUsersApiChatUsersGetData>> =>
  createQueryKey('listChatUsersApiChatUsersGet', options, true)

/**
 * List Chat Users
 *
 * List all chat users with pagination.
 *
 * Optional search by name or id and filter by chat membership.
 */
export const listChatUsersApiChatUsersGetInfiniteOptions = (
  options?: Options<ListChatUsersApiChatUsersGetData>,
) =>
  infiniteQueryOptions<
    ListChatUsersApiChatUsersGetResponse,
    ListChatUsersApiChatUsersGetError,
    InfiniteData<ListChatUsersApiChatUsersGetResponse>,
    QueryKey<Options<ListChatUsersApiChatUsersGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListChatUsersApiChatUsersGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListChatUsersApiChatUsersGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await listChatUsersApiChatUsersGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: listChatUsersApiChatUsersGetInfiniteQueryKey(options),
    },
  )

export const getChatUserApiChatUsersUserIdGetQueryKey = (
  options: Options<GetChatUserApiChatUsersUserIdGetData>,
) => createQueryKey('getChatUserApiChatUsersUserIdGet', options)

/**
 * Get Chat User
 *
 * Get chat user by ID with roles and chats.
 */
export const getChatUserApiChatUsersUserIdGetOptions = (
  options: Options<GetChatUserApiChatUsersUserIdGetData>,
) =>
  queryOptions<
    GetChatUserApiChatUsersUserIdGetResponse,
    GetChatUserApiChatUsersUserIdGetError,
    GetChatUserApiChatUsersUserIdGetResponse,
    ReturnType<typeof getChatUserApiChatUsersUserIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getChatUserApiChatUsersUserIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getChatUserApiChatUsersUserIdGetQueryKey(options),
  })

/**
 * Update Chat User
 *
 * Update chat user. Owner only.
 */
export const updateChatUserApiChatUsersUserIdPatchMutation = (
  options?: Partial<Options<UpdateChatUserApiChatUsersUserIdPatchData>>,
): UseMutationOptions<
  UpdateChatUserApiChatUsersUserIdPatchResponse,
  UpdateChatUserApiChatUsersUserIdPatchError,
  Options<UpdateChatUserApiChatUsersUserIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateChatUserApiChatUsersUserIdPatchResponse,
    UpdateChatUserApiChatUsersUserIdPatchError,
    Options<UpdateChatUserApiChatUsersUserIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateChatUserApiChatUsersUserIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Remove Role From User
 *
 * Remove role from chat user. Admin only.
 */
export const removeRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteMutation = (
  options?: Partial<Options<RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteData>>,
): UseMutationOptions<
  RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteResponse,
  RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteError,
  Options<RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteResponse,
    RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteError,
    Options<RemoveRoleFromUserApiChatUsersUserIdRolesRoleIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await removeRoleFromUserApiChatUsersUserIdRolesRoleIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Assign Role To User
 *
 * Assign role to chat user. Admin only.
 */
export const assignRoleToUserApiChatUsersUserIdRolesRoleIdPostMutation = (
  options?: Partial<Options<AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostData>>,
): UseMutationOptions<
  AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostResponse,
  AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostError,
  Options<AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostData>
> => {
  const mutationOptions: UseMutationOptions<
    AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostResponse,
    AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostError,
    Options<AssignRoleToUserApiChatUsersUserIdRolesRoleIdPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await assignRoleToUserApiChatUsersUserIdRolesRoleIdPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getBotSettingApiBotSettingsKeyGetQueryKey = (
  options: Options<GetBotSettingApiBotSettingsKeyGetData>,
) => createQueryKey('getBotSettingApiBotSettingsKeyGet', options)

/**
 * Get Bot Setting
 *
 * Get bot setting by key. Admin only.
 */
export const getBotSettingApiBotSettingsKeyGetOptions = (
  options: Options<GetBotSettingApiBotSettingsKeyGetData>,
) =>
  queryOptions<
    GetBotSettingApiBotSettingsKeyGetResponse,
    GetBotSettingApiBotSettingsKeyGetError,
    GetBotSettingApiBotSettingsKeyGetResponse,
    ReturnType<typeof getBotSettingApiBotSettingsKeyGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getBotSettingApiBotSettingsKeyGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getBotSettingApiBotSettingsKeyGetQueryKey(options),
  })

/**
 * Update Bot Setting
 *
 * Update or create bot setting. Admin only.
 */
export const updateBotSettingApiBotSettingsKeyPutMutation = (
  options?: Partial<Options<UpdateBotSettingApiBotSettingsKeyPutData>>,
): UseMutationOptions<
  UpdateBotSettingApiBotSettingsKeyPutResponse,
  UpdateBotSettingApiBotSettingsKeyPutError,
  Options<UpdateBotSettingApiBotSettingsKeyPutData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateBotSettingApiBotSettingsKeyPutResponse,
    UpdateBotSettingApiBotSettingsKeyPutError,
    Options<UpdateBotSettingApiBotSettingsKeyPutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateBotSettingApiBotSettingsKeyPut({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listBotSettingsApiBotSettingsGetQueryKey = (
  options?: Options<ListBotSettingsApiBotSettingsGetData>,
) => createQueryKey('listBotSettingsApiBotSettingsGet', options)

/**
 * List Bot Settings
 *
 * List all bot settings. Admin only.
 */
export const listBotSettingsApiBotSettingsGetOptions = (
  options?: Options<ListBotSettingsApiBotSettingsGetData>,
) =>
  queryOptions<
    ListBotSettingsApiBotSettingsGetResponse,
    DefaultError,
    ListBotSettingsApiBotSettingsGetResponse,
    ReturnType<typeof listBotSettingsApiBotSettingsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listBotSettingsApiBotSettingsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listBotSettingsApiBotSettingsGetQueryKey(options),
  })

export const listEventTypesApiEventsTypesGetQueryKey = (
  options?: Options<ListEventTypesApiEventsTypesGetData>,
) => createQueryKey('listEventTypesApiEventsTypesGet', options)

/**
 * List Event Types
 *
 * Реестр типов событий.
 *
 * Панель строит по нему подписи и список фильтров — иначе словарь
 * названий пришлось бы держать во фронтенде и синхронизировать руками,
 * а типы плагинов туда не попали бы вовсе.
 */
export const listEventTypesApiEventsTypesGetOptions = (
  options?: Options<ListEventTypesApiEventsTypesGetData>,
) =>
  queryOptions<
    ListEventTypesApiEventsTypesGetResponse,
    DefaultError,
    ListEventTypesApiEventsTypesGetResponse,
    ReturnType<typeof listEventTypesApiEventsTypesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listEventTypesApiEventsTypesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listEventTypesApiEventsTypesGetQueryKey(options),
  })

export const listEventsApiEventsGetQueryKey = (options?: Options<ListEventsApiEventsGetData>) =>
  createQueryKey('listEventsApiEventsGet', options)

/**
 * List Events
 *
 * Лента событий.
 *
 * Админ видит всё. Обычный участник — события чатов, в которых
 * состоит, и без текстов сообщений.
 */
export const listEventsApiEventsGetOptions = (options?: Options<ListEventsApiEventsGetData>) =>
  queryOptions<
    ListEventsApiEventsGetResponse,
    ListEventsApiEventsGetError,
    ListEventsApiEventsGetResponse,
    ReturnType<typeof listEventsApiEventsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listEventsApiEventsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listEventsApiEventsGetQueryKey(options),
  })

export const listEventsApiEventsGetInfiniteQueryKey = (
  options?: Options<ListEventsApiEventsGetData>,
): QueryKey<Options<ListEventsApiEventsGetData>> =>
  createQueryKey('listEventsApiEventsGet', options, true)

/**
 * List Events
 *
 * Лента событий.
 *
 * Админ видит всё. Обычный участник — события чатов, в которых
 * состоит, и без текстов сообщений.
 */
export const listEventsApiEventsGetInfiniteOptions = (
  options?: Options<ListEventsApiEventsGetData>,
) =>
  infiniteQueryOptions<
    ListEventsApiEventsGetResponse,
    ListEventsApiEventsGetError,
    InfiniteData<ListEventsApiEventsGetResponse>,
    QueryKey<Options<ListEventsApiEventsGetData>>,
    | number
    | Pick<QueryKey<Options<ListEventsApiEventsGetData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListEventsApiEventsGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await listEventsApiEventsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: listEventsApiEventsGetInfiniteQueryKey(options),
    },
  )

export const getEventApiEventsEventIdGetQueryKey = (
  options: Options<GetEventApiEventsEventIdGetData>,
) => createQueryKey('getEventApiEventsEventIdGet', options)

/**
 * Get Event
 *
 * Одно событие.
 */
export const getEventApiEventsEventIdGetOptions = (
  options: Options<GetEventApiEventsEventIdGetData>,
) =>
  queryOptions<
    GetEventApiEventsEventIdGetResponse,
    GetEventApiEventsEventIdGetError,
    GetEventApiEventsEventIdGetResponse,
    ReturnType<typeof getEventApiEventsEventIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEventApiEventsEventIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getEventApiEventsEventIdGetQueryKey(options),
  })

export const getOverviewApiOverviewGetQueryKey = (
  options?: Options<GetOverviewApiOverviewGetData>,
) => createQueryKey('getOverviewApiOverviewGet', options)

/**
 * Get Overview
 *
 * Счётчики и активность для главной страницы.
 */
export const getOverviewApiOverviewGetOptions = (
  options?: Options<GetOverviewApiOverviewGetData>,
) =>
  queryOptions<
    GetOverviewApiOverviewGetResponse,
    GetOverviewApiOverviewGetError,
    GetOverviewApiOverviewGetResponse,
    ReturnType<typeof getOverviewApiOverviewGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getOverviewApiOverviewGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getOverviewApiOverviewGetQueryKey(options),
  })

export const listWebhooksApiWebhooksGetQueryKey = (
  options?: Options<ListWebhooksApiWebhooksGetData>,
) => createQueryKey('listWebhooksApiWebhooksGet', options)

/**
 * List Webhooks
 *
 * Получить список вебхуков пользователя.
 */
export const listWebhooksApiWebhooksGetOptions = (
  options?: Options<ListWebhooksApiWebhooksGetData>,
) =>
  queryOptions<
    ListWebhooksApiWebhooksGetResponse,
    DefaultError,
    ListWebhooksApiWebhooksGetResponse,
    ReturnType<typeof listWebhooksApiWebhooksGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listWebhooksApiWebhooksGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listWebhooksApiWebhooksGetQueryKey(options),
  })

/**
 * Create Webhook
 *
 * Создать новый вебхук.
 */
export const createWebhookApiWebhooksPostMutation = (
  options?: Partial<Options<CreateWebhookApiWebhooksPostData>>,
): UseMutationOptions<
  CreateWebhookApiWebhooksPostResponse,
  CreateWebhookApiWebhooksPostError,
  Options<CreateWebhookApiWebhooksPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateWebhookApiWebhooksPostResponse,
    CreateWebhookApiWebhooksPostError,
    Options<CreateWebhookApiWebhooksPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createWebhookApiWebhooksPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete Webhook
 *
 * Удалить вебхук.
 */
export const deleteWebhookApiWebhooksWebhookIdDeleteMutation = (
  options?: Partial<Options<DeleteWebhookApiWebhooksWebhookIdDeleteData>>,
): UseMutationOptions<
  DeleteWebhookApiWebhooksWebhookIdDeleteResponse,
  DeleteWebhookApiWebhooksWebhookIdDeleteError,
  Options<DeleteWebhookApiWebhooksWebhookIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteWebhookApiWebhooksWebhookIdDeleteResponse,
    DeleteWebhookApiWebhooksWebhookIdDeleteError,
    Options<DeleteWebhookApiWebhooksWebhookIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteWebhookApiWebhooksWebhookIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getWebhookApiWebhooksWebhookIdGetQueryKey = (
  options: Options<GetWebhookApiWebhooksWebhookIdGetData>,
) => createQueryKey('getWebhookApiWebhooksWebhookIdGet', options)

/**
 * Get Webhook
 *
 * Получить информацию о вебхуке.
 */
export const getWebhookApiWebhooksWebhookIdGetOptions = (
  options: Options<GetWebhookApiWebhooksWebhookIdGetData>,
) =>
  queryOptions<
    GetWebhookApiWebhooksWebhookIdGetResponse,
    GetWebhookApiWebhooksWebhookIdGetError,
    GetWebhookApiWebhooksWebhookIdGetResponse,
    ReturnType<typeof getWebhookApiWebhooksWebhookIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWebhookApiWebhooksWebhookIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getWebhookApiWebhooksWebhookIdGetQueryKey(options),
  })

/**
 * Update Webhook
 *
 * Обновить вебхук.
 */
export const updateWebhookApiWebhooksWebhookIdPutMutation = (
  options?: Partial<Options<UpdateWebhookApiWebhooksWebhookIdPutData>>,
): UseMutationOptions<
  UpdateWebhookApiWebhooksWebhookIdPutResponse,
  UpdateWebhookApiWebhooksWebhookIdPutError,
  Options<UpdateWebhookApiWebhooksWebhookIdPutData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateWebhookApiWebhooksWebhookIdPutResponse,
    UpdateWebhookApiWebhooksWebhookIdPutError,
    Options<UpdateWebhookApiWebhooksWebhookIdPutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateWebhookApiWebhooksWebhookIdPut({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Regenerate Webhook Api Key
 *
 * Перегенерировать API ключ для вебхука.
 */
export const regenerateWebhookApiKeyApiWebhooksWebhookIdRegeneratePostMutation = (
  options?: Partial<Options<RegenerateWebhookApiKeyApiWebhooksWebhookIdRegeneratePostData>>,
): UseMutationOptions<
  RegenerateWebhookApiKeyApiWebhooksWebhookIdRegeneratePostResponse,
  RegenerateWebhookApiKeyApiWebhooksWebhookIdRegeneratePostError,
  Options<RegenerateWebhookApiKeyApiWebhooksWebhookIdRegeneratePostData>
> => {
  const mutationOptions: UseMutationOptions<
    RegenerateWebhookApiKeyApiWebhooksWebhookIdRegeneratePostResponse,
    RegenerateWebhookApiKeyApiWebhooksWebhookIdRegeneratePostError,
    Options<RegenerateWebhookApiKeyApiWebhooksWebhookIdRegeneratePostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await regenerateWebhookApiKeyApiWebhooksWebhookIdRegeneratePost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Handle Webhook
 *
 * Универсальный обработчик для всех вебхуков.
 */
export const handleWebhookWebhooksWebhookIdPostMutation = (
  options?: Partial<Options<HandleWebhookWebhooksWebhookIdPostData>>,
): UseMutationOptions<
  HandleWebhookWebhooksWebhookIdPostResponse,
  HandleWebhookWebhooksWebhookIdPostError,
  Options<HandleWebhookWebhooksWebhookIdPostData>
> => {
  const mutationOptions: UseMutationOptions<
    HandleWebhookWebhooksWebhookIdPostResponse,
    HandleWebhookWebhooksWebhookIdPostError,
    Options<HandleWebhookWebhooksWebhookIdPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await handleWebhookWebhooksWebhookIdPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const rootGetQueryKey = (options?: Options<RootGetData>) =>
  createQueryKey('rootGet', options)

/**
 * Root
 */
export const rootGetOptions = (options?: Options<RootGetData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof rootGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await rootGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: rootGetQueryKey(options),
  })

export const healthHealthGetQueryKey = (options?: Options<HealthHealthGetData>) =>
  createQueryKey('healthHealthGet', options)

/**
 * Health
 */
export const healthHealthGetOptions = (options?: Options<HealthHealthGetData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof healthHealthGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthHealthGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: healthHealthGetQueryKey(options),
  })

export const getStatusApiAiStatusGetQueryKey = (options?: Options<GetStatusApiAiStatusGetData>) =>
  createQueryKey('getStatusApiAiStatusGet', options)

/**
 * Get Status
 *
 * Включён ли агент и с какими лимитами.
 *
 * Панель без этого не отличила бы «агента выключили» от «никто ещё не
 * спрашивал»: и там, и там пустой список.
 */
export const getStatusApiAiStatusGetOptions = (options?: Options<GetStatusApiAiStatusGetData>) =>
  queryOptions<
    GetStatusApiAiStatusGetResponse,
    DefaultError,
    GetStatusApiAiStatusGetResponse,
    ReturnType<typeof getStatusApiAiStatusGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getStatusApiAiStatusGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getStatusApiAiStatusGetQueryKey(options),
  })

export const listSessionsApiAiSessionsGetQueryKey = (
  options?: Options<ListSessionsApiAiSessionsGetData>,
) => createQueryKey('listSessionsApiAiSessionsGet', options)

/**
 * List Sessions
 *
 * Диалоги с агентом.
 *
 * Админ видит все, остальные — только свои: фильтр по участнику для них
 * не расширяет выдачу, а сужает её внутри собственных сессий.
 */
export const listSessionsApiAiSessionsGetOptions = (
  options?: Options<ListSessionsApiAiSessionsGetData>,
) =>
  queryOptions<
    ListSessionsApiAiSessionsGetResponse,
    ListSessionsApiAiSessionsGetError,
    ListSessionsApiAiSessionsGetResponse,
    ReturnType<typeof listSessionsApiAiSessionsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listSessionsApiAiSessionsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listSessionsApiAiSessionsGetQueryKey(options),
  })

export const listSessionsApiAiSessionsGetInfiniteQueryKey = (
  options?: Options<ListSessionsApiAiSessionsGetData>,
): QueryKey<Options<ListSessionsApiAiSessionsGetData>> =>
  createQueryKey('listSessionsApiAiSessionsGet', options, true)

/**
 * List Sessions
 *
 * Диалоги с агентом.
 *
 * Админ видит все, остальные — только свои: фильтр по участнику для них
 * не расширяет выдачу, а сужает её внутри собственных сессий.
 */
export const listSessionsApiAiSessionsGetInfiniteOptions = (
  options?: Options<ListSessionsApiAiSessionsGetData>,
) =>
  infiniteQueryOptions<
    ListSessionsApiAiSessionsGetResponse,
    ListSessionsApiAiSessionsGetError,
    InfiniteData<ListSessionsApiAiSessionsGetResponse>,
    QueryKey<Options<ListSessionsApiAiSessionsGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListSessionsApiAiSessionsGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListSessionsApiAiSessionsGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await listSessionsApiAiSessionsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: listSessionsApiAiSessionsGetInfiniteQueryKey(options),
    },
  )

export const getSessionApiAiSessionsSessionIdGetQueryKey = (
  options: Options<GetSessionApiAiSessionsSessionIdGetData>,
) => createQueryKey('getSessionApiAiSessionsSessionIdGet', options)

/**
 * Get Session
 *
 * Ход одного диалога.
 */
export const getSessionApiAiSessionsSessionIdGetOptions = (
  options: Options<GetSessionApiAiSessionsSessionIdGetData>,
) =>
  queryOptions<
    GetSessionApiAiSessionsSessionIdGetResponse,
    GetSessionApiAiSessionsSessionIdGetError,
    GetSessionApiAiSessionsSessionIdGetResponse,
    ReturnType<typeof getSessionApiAiSessionsSessionIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSessionApiAiSessionsSessionIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getSessionApiAiSessionsSessionIdGetQueryKey(options),
  })

export const getUsageApiAiUsageGetQueryKey = (options?: Options<GetUsageApiAiUsageGetData>) =>
  createQueryKey('getUsageApiAiUsageGet', options)

/**
 * Get Usage
 *
 * Расход токенов за период.
 *
 * Админ видит всех, обычный участник — только себя. Топы у него пустые
 * не потому, что данных нет, а потому что чужой расход — это чужая
 * активность.
 */
export const getUsageApiAiUsageGetOptions = (options?: Options<GetUsageApiAiUsageGetData>) =>
  queryOptions<
    GetUsageApiAiUsageGetResponse,
    GetUsageApiAiUsageGetError,
    GetUsageApiAiUsageGetResponse,
    ReturnType<typeof getUsageApiAiUsageGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUsageApiAiUsageGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getUsageApiAiUsageGetQueryKey(options),
  })

export const listWebhooksGlWebhooksGetQueryKey = (
  options?: Options<ListWebhooksGlWebhooksGetData>,
) => createQueryKey('listWebhooksGlWebhooksGet', options)

/**
 * List Webhooks
 *
 * List all GitLab webhooks with pagination.
 */
export const listWebhooksGlWebhooksGetOptions = (
  options?: Options<ListWebhooksGlWebhooksGetData>,
) =>
  queryOptions<
    ListWebhooksGlWebhooksGetResponse,
    ListWebhooksGlWebhooksGetError,
    ListWebhooksGlWebhooksGetResponse,
    ReturnType<typeof listWebhooksGlWebhooksGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listWebhooksGlWebhooksGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listWebhooksGlWebhooksGetQueryKey(options),
  })

export const listWebhooksGlWebhooksGetInfiniteQueryKey = (
  options?: Options<ListWebhooksGlWebhooksGetData>,
): QueryKey<Options<ListWebhooksGlWebhooksGetData>> =>
  createQueryKey('listWebhooksGlWebhooksGet', options, true)

/**
 * List Webhooks
 *
 * List all GitLab webhooks with pagination.
 */
export const listWebhooksGlWebhooksGetInfiniteOptions = (
  options?: Options<ListWebhooksGlWebhooksGetData>,
) =>
  infiniteQueryOptions<
    ListWebhooksGlWebhooksGetResponse,
    ListWebhooksGlWebhooksGetError,
    InfiniteData<ListWebhooksGlWebhooksGetResponse>,
    QueryKey<Options<ListWebhooksGlWebhooksGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListWebhooksGlWebhooksGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListWebhooksGlWebhooksGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await listWebhooksGlWebhooksGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: listWebhooksGlWebhooksGetInfiniteQueryKey(options),
    },
  )

/**
 * Create Webhook
 *
 * Create a new GitLab webhook.
 */
export const createWebhookGlWebhooksPostMutation = (
  options?: Partial<Options<CreateWebhookGlWebhooksPostData>>,
): UseMutationOptions<
  CreateWebhookGlWebhooksPostResponse,
  CreateWebhookGlWebhooksPostError,
  Options<CreateWebhookGlWebhooksPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateWebhookGlWebhooksPostResponse,
    CreateWebhookGlWebhooksPostError,
    Options<CreateWebhookGlWebhooksPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createWebhookGlWebhooksPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete Webhook
 *
 * Delete a GitLab webhook.
 */
export const deleteWebhookGlWebhooksWebhookIdDeleteMutation = (
  options?: Partial<Options<DeleteWebhookGlWebhooksWebhookIdDeleteData>>,
): UseMutationOptions<
  DeleteWebhookGlWebhooksWebhookIdDeleteResponse,
  DeleteWebhookGlWebhooksWebhookIdDeleteError,
  Options<DeleteWebhookGlWebhooksWebhookIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteWebhookGlWebhooksWebhookIdDeleteResponse,
    DeleteWebhookGlWebhooksWebhookIdDeleteError,
    Options<DeleteWebhookGlWebhooksWebhookIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteWebhookGlWebhooksWebhookIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getWebhookGlWebhooksWebhookIdGetQueryKey = (
  options: Options<GetWebhookGlWebhooksWebhookIdGetData>,
) => createQueryKey('getWebhookGlWebhooksWebhookIdGet', options)

/**
 * Get Webhook
 *
 * Get a specific GitLab webhook by ID.
 */
export const getWebhookGlWebhooksWebhookIdGetOptions = (
  options: Options<GetWebhookGlWebhooksWebhookIdGetData>,
) =>
  queryOptions<
    GetWebhookGlWebhooksWebhookIdGetResponse,
    GetWebhookGlWebhooksWebhookIdGetError,
    GetWebhookGlWebhooksWebhookIdGetResponse,
    ReturnType<typeof getWebhookGlWebhooksWebhookIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWebhookGlWebhooksWebhookIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getWebhookGlWebhooksWebhookIdGetQueryKey(options),
  })

/**
 * Update Webhook
 *
 * Update a GitLab webhook.
 */
export const updateWebhookGlWebhooksWebhookIdPatchMutation = (
  options?: Partial<Options<UpdateWebhookGlWebhooksWebhookIdPatchData>>,
): UseMutationOptions<
  UpdateWebhookGlWebhooksWebhookIdPatchResponse,
  UpdateWebhookGlWebhooksWebhookIdPatchError,
  Options<UpdateWebhookGlWebhooksWebhookIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateWebhookGlWebhooksWebhookIdPatchResponse,
    UpdateWebhookGlWebhooksWebhookIdPatchError,
    Options<UpdateWebhookGlWebhooksWebhookIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateWebhookGlWebhooksWebhookIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Trigger Webhook
 *
 * GitLab webhook trigger endpoint.
 */
export const triggerWebhookGlWebhooksWebhookIdTriggerPostMutation = (
  options?: Partial<Options<TriggerWebhookGlWebhooksWebhookIdTriggerPostData>>,
): UseMutationOptions<
  unknown,
  TriggerWebhookGlWebhooksWebhookIdTriggerPostError,
  Options<TriggerWebhookGlWebhooksWebhookIdTriggerPostData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    TriggerWebhookGlWebhooksWebhookIdTriggerPostError,
    Options<TriggerWebhookGlWebhooksWebhookIdTriggerPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await triggerWebhookGlWebhooksWebhookIdTriggerPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}
