// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/vue-query';

import { client } from '../client.gen';
import { addRoleMemberApiRolesRoleIdMembersPost, createRoleApiRolesPost, createUserApiUsersPost, deleteRoleApiRolesRoleIdDelete, deleteUserApiUsersUsernameDelete, getChatApiChatsChatIdGet, getCurrentUserInfoApiAuthMeGet, getRoleApiRolesRoleIdGet, getUserApiUsersUsernameGet, healthHealthGet, listChatsApiChatsGet, listRoleMembersApiRolesRoleIdMembersGet, listRolesApiRolesGet, listUsersApiUsersGet, loginApiAuthLoginPost, type Options, removeRoleMemberApiRolesRoleIdMembersUserIdDelete, rootGet, updateRoleApiRolesRoleIdPatch, updateUserApiUsersUsernamePatch } from '../sdk.gen';
import type { AddRoleMemberApiRolesRoleIdMembersPostData, AddRoleMemberApiRolesRoleIdMembersPostError, AddRoleMemberApiRolesRoleIdMembersPostResponse, CreateRoleApiRolesPostData, CreateRoleApiRolesPostError, CreateRoleApiRolesPostResponse, CreateUserApiUsersPostData, CreateUserApiUsersPostError, CreateUserApiUsersPostResponse, DeleteRoleApiRolesRoleIdDeleteData, DeleteRoleApiRolesRoleIdDeleteError, DeleteRoleApiRolesRoleIdDeleteResponse, DeleteUserApiUsersUsernameDeleteData, DeleteUserApiUsersUsernameDeleteError, DeleteUserApiUsersUsernameDeleteResponse, GetChatApiChatsChatIdGetData, GetChatApiChatsChatIdGetError, GetChatApiChatsChatIdGetResponse, GetCurrentUserInfoApiAuthMeGetData, GetCurrentUserInfoApiAuthMeGetResponse, GetRoleApiRolesRoleIdGetData, GetRoleApiRolesRoleIdGetError, GetRoleApiRolesRoleIdGetResponse, GetUserApiUsersUsernameGetData, GetUserApiUsersUsernameGetError, GetUserApiUsersUsernameGetResponse, HealthHealthGetData, ListChatsApiChatsGetData, ListChatsApiChatsGetError, ListChatsApiChatsGetResponse, ListRoleMembersApiRolesRoleIdMembersGetData, ListRoleMembersApiRolesRoleIdMembersGetError, ListRoleMembersApiRolesRoleIdMembersGetResponse, ListRolesApiRolesGetData, ListRolesApiRolesGetError, ListRolesApiRolesGetResponse, ListUsersApiUsersGetData, ListUsersApiUsersGetError, ListUsersApiUsersGetResponse, LoginApiAuthLoginPostData, LoginApiAuthLoginPostError, LoginApiAuthLoginPostResponse, RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteData, RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteError, RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteResponse, RootGetData, UpdateRoleApiRolesRoleIdPatchData, UpdateRoleApiRolesRoleIdPatchError, UpdateRoleApiRolesRoleIdPatchResponse, UpdateUserApiUsersUsernamePatchData, UpdateUserApiUsersUsernamePatchError, UpdateUserApiUsersUsernamePatchResponse } from '../types.gen';

/**
 * Login
 *
 * Login and get JWT token.
 */
export const loginApiAuthLoginPostMutation = (options?: Partial<Options<LoginApiAuthLoginPostData>>): UseMutationOptions<LoginApiAuthLoginPostResponse, LoginApiAuthLoginPostError, Options<LoginApiAuthLoginPostData>> => {
    const mutationOptions: UseMutationOptions<LoginApiAuthLoginPostResponse, LoginApiAuthLoginPostError, Options<LoginApiAuthLoginPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await loginApiAuthLoginPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getCurrentUserInfoApiAuthMeGetQueryKey = (options?: Options<GetCurrentUserInfoApiAuthMeGetData>) => createQueryKey('getCurrentUserInfoApiAuthMeGet', options);

/**
 * Get Current User Info
 *
 * Get current authenticated user information.
 */
export const getCurrentUserInfoApiAuthMeGetOptions = (options?: Options<GetCurrentUserInfoApiAuthMeGetData>) => queryOptions<GetCurrentUserInfoApiAuthMeGetResponse, DefaultError, GetCurrentUserInfoApiAuthMeGetResponse, ReturnType<typeof getCurrentUserInfoApiAuthMeGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCurrentUserInfoApiAuthMeGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCurrentUserInfoApiAuthMeGetQueryKey(options)
});

export const listUsersApiUsersGetQueryKey = (options?: Options<ListUsersApiUsersGetData>) => createQueryKey('listUsersApiUsersGet', options);

/**
 * List Users
 *
 * List all users with pagination. Admin only.
 */
export const listUsersApiUsersGetOptions = (options?: Options<ListUsersApiUsersGetData>) => queryOptions<ListUsersApiUsersGetResponse, ListUsersApiUsersGetError, ListUsersApiUsersGetResponse, ReturnType<typeof listUsersApiUsersGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listUsersApiUsersGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listUsersApiUsersGetQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const listUsersApiUsersGetInfiniteQueryKey = (options?: Options<ListUsersApiUsersGetData>): QueryKey<Options<ListUsersApiUsersGetData>> => createQueryKey('listUsersApiUsersGet', options, true);

/**
 * List Users
 *
 * List all users with pagination. Admin only.
 */
export const listUsersApiUsersGetInfiniteOptions = (options?: Options<ListUsersApiUsersGetData>) => infiniteQueryOptions<ListUsersApiUsersGetResponse, ListUsersApiUsersGetError, InfiniteData<ListUsersApiUsersGetResponse>, QueryKey<Options<ListUsersApiUsersGetData>>, number | Pick<QueryKey<Options<ListUsersApiUsersGetData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ListUsersApiUsersGetData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listUsersApiUsersGet({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listUsersApiUsersGetInfiniteQueryKey(options)
});

/**
 * Create User
 *
 * Create new user. Admin only.
 */
export const createUserApiUsersPostMutation = (options?: Partial<Options<CreateUserApiUsersPostData>>): UseMutationOptions<CreateUserApiUsersPostResponse, CreateUserApiUsersPostError, Options<CreateUserApiUsersPostData>> => {
    const mutationOptions: UseMutationOptions<CreateUserApiUsersPostResponse, CreateUserApiUsersPostError, Options<CreateUserApiUsersPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createUserApiUsersPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete User
 *
 * Delete user. Admin only.
 */
export const deleteUserApiUsersUsernameDeleteMutation = (options?: Partial<Options<DeleteUserApiUsersUsernameDeleteData>>): UseMutationOptions<DeleteUserApiUsersUsernameDeleteResponse, DeleteUserApiUsersUsernameDeleteError, Options<DeleteUserApiUsersUsernameDeleteData>> => {
    const mutationOptions: UseMutationOptions<DeleteUserApiUsersUsernameDeleteResponse, DeleteUserApiUsersUsernameDeleteError, Options<DeleteUserApiUsersUsernameDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteUserApiUsersUsernameDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUserApiUsersUsernameGetQueryKey = (options: Options<GetUserApiUsersUsernameGetData>) => createQueryKey('getUserApiUsersUsernameGet', options);

/**
 * Get User
 *
 * Get user by username. Admin only.
 */
export const getUserApiUsersUsernameGetOptions = (options: Options<GetUserApiUsersUsernameGetData>) => queryOptions<GetUserApiUsersUsernameGetResponse, GetUserApiUsersUsernameGetError, GetUserApiUsersUsernameGetResponse, ReturnType<typeof getUserApiUsersUsernameGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUserApiUsersUsernameGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserApiUsersUsernameGetQueryKey(options)
});

/**
 * Update User
 *
 * Update user. Admin only.
 */
export const updateUserApiUsersUsernamePatchMutation = (options?: Partial<Options<UpdateUserApiUsersUsernamePatchData>>): UseMutationOptions<UpdateUserApiUsersUsernamePatchResponse, UpdateUserApiUsersUsernamePatchError, Options<UpdateUserApiUsersUsernamePatchData>> => {
    const mutationOptions: UseMutationOptions<UpdateUserApiUsersUsernamePatchResponse, UpdateUserApiUsersUsernamePatchError, Options<UpdateUserApiUsersUsernamePatchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateUserApiUsersUsernamePatch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listChatsApiChatsGetQueryKey = (options?: Options<ListChatsApiChatsGetData>) => createQueryKey('listChatsApiChatsGet', options);

/**
 * List Chats
 *
 * List all chats with pagination. Admin only.
 */
export const listChatsApiChatsGetOptions = (options?: Options<ListChatsApiChatsGetData>) => queryOptions<ListChatsApiChatsGetResponse, ListChatsApiChatsGetError, ListChatsApiChatsGetResponse, ReturnType<typeof listChatsApiChatsGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listChatsApiChatsGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listChatsApiChatsGetQueryKey(options)
});

export const listChatsApiChatsGetInfiniteQueryKey = (options?: Options<ListChatsApiChatsGetData>): QueryKey<Options<ListChatsApiChatsGetData>> => createQueryKey('listChatsApiChatsGet', options, true);

/**
 * List Chats
 *
 * List all chats with pagination. Admin only.
 */
export const listChatsApiChatsGetInfiniteOptions = (options?: Options<ListChatsApiChatsGetData>) => infiniteQueryOptions<ListChatsApiChatsGetResponse, ListChatsApiChatsGetError, InfiniteData<ListChatsApiChatsGetResponse>, QueryKey<Options<ListChatsApiChatsGetData>>, number | Pick<QueryKey<Options<ListChatsApiChatsGetData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ListChatsApiChatsGetData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listChatsApiChatsGet({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listChatsApiChatsGetInfiniteQueryKey(options)
});

export const getChatApiChatsChatIdGetQueryKey = (options: Options<GetChatApiChatsChatIdGetData>) => createQueryKey('getChatApiChatsChatIdGet', options);

/**
 * Get Chat
 *
 * Get chat by ID. Admin only.
 */
export const getChatApiChatsChatIdGetOptions = (options: Options<GetChatApiChatsChatIdGetData>) => queryOptions<GetChatApiChatsChatIdGetResponse, GetChatApiChatsChatIdGetError, GetChatApiChatsChatIdGetResponse, ReturnType<typeof getChatApiChatsChatIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getChatApiChatsChatIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getChatApiChatsChatIdGetQueryKey(options)
});

export const listRolesApiRolesGetQueryKey = (options?: Options<ListRolesApiRolesGetData>) => createQueryKey('listRolesApiRolesGet', options);

/**
 * List Roles
 *
 * List all roles with pagination. Admin only.
 */
export const listRolesApiRolesGetOptions = (options?: Options<ListRolesApiRolesGetData>) => queryOptions<ListRolesApiRolesGetResponse, ListRolesApiRolesGetError, ListRolesApiRolesGetResponse, ReturnType<typeof listRolesApiRolesGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listRolesApiRolesGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listRolesApiRolesGetQueryKey(options)
});

export const listRolesApiRolesGetInfiniteQueryKey = (options?: Options<ListRolesApiRolesGetData>): QueryKey<Options<ListRolesApiRolesGetData>> => createQueryKey('listRolesApiRolesGet', options, true);

/**
 * List Roles
 *
 * List all roles with pagination. Admin only.
 */
export const listRolesApiRolesGetInfiniteOptions = (options?: Options<ListRolesApiRolesGetData>) => infiniteQueryOptions<ListRolesApiRolesGetResponse, ListRolesApiRolesGetError, InfiniteData<ListRolesApiRolesGetResponse>, QueryKey<Options<ListRolesApiRolesGetData>>, number | Pick<QueryKey<Options<ListRolesApiRolesGetData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ListRolesApiRolesGetData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listRolesApiRolesGet({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listRolesApiRolesGetInfiniteQueryKey(options)
});

/**
 * Create Role
 *
 * Create new role. Admin only.
 */
export const createRoleApiRolesPostMutation = (options?: Partial<Options<CreateRoleApiRolesPostData>>): UseMutationOptions<CreateRoleApiRolesPostResponse, CreateRoleApiRolesPostError, Options<CreateRoleApiRolesPostData>> => {
    const mutationOptions: UseMutationOptions<CreateRoleApiRolesPostResponse, CreateRoleApiRolesPostError, Options<CreateRoleApiRolesPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createRoleApiRolesPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Role
 *
 * Delete role. Admin only.
 */
export const deleteRoleApiRolesRoleIdDeleteMutation = (options?: Partial<Options<DeleteRoleApiRolesRoleIdDeleteData>>): UseMutationOptions<DeleteRoleApiRolesRoleIdDeleteResponse, DeleteRoleApiRolesRoleIdDeleteError, Options<DeleteRoleApiRolesRoleIdDeleteData>> => {
    const mutationOptions: UseMutationOptions<DeleteRoleApiRolesRoleIdDeleteResponse, DeleteRoleApiRolesRoleIdDeleteError, Options<DeleteRoleApiRolesRoleIdDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteRoleApiRolesRoleIdDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRoleApiRolesRoleIdGetQueryKey = (options: Options<GetRoleApiRolesRoleIdGetData>) => createQueryKey('getRoleApiRolesRoleIdGet', options);

/**
 * Get Role
 *
 * Get role by ID with its members. Admin only.
 */
export const getRoleApiRolesRoleIdGetOptions = (options: Options<GetRoleApiRolesRoleIdGetData>) => queryOptions<GetRoleApiRolesRoleIdGetResponse, GetRoleApiRolesRoleIdGetError, GetRoleApiRolesRoleIdGetResponse, ReturnType<typeof getRoleApiRolesRoleIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRoleApiRolesRoleIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRoleApiRolesRoleIdGetQueryKey(options)
});

/**
 * Update Role
 *
 * Update role. Admin only.
 */
export const updateRoleApiRolesRoleIdPatchMutation = (options?: Partial<Options<UpdateRoleApiRolesRoleIdPatchData>>): UseMutationOptions<UpdateRoleApiRolesRoleIdPatchResponse, UpdateRoleApiRolesRoleIdPatchError, Options<UpdateRoleApiRolesRoleIdPatchData>> => {
    const mutationOptions: UseMutationOptions<UpdateRoleApiRolesRoleIdPatchResponse, UpdateRoleApiRolesRoleIdPatchError, Options<UpdateRoleApiRolesRoleIdPatchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateRoleApiRolesRoleIdPatch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listRoleMembersApiRolesRoleIdMembersGetQueryKey = (options: Options<ListRoleMembersApiRolesRoleIdMembersGetData>) => createQueryKey('listRoleMembersApiRolesRoleIdMembersGet', options);

/**
 * List Role Members
 *
 * List all members of a role. Admin only.
 */
export const listRoleMembersApiRolesRoleIdMembersGetOptions = (options: Options<ListRoleMembersApiRolesRoleIdMembersGetData>) => queryOptions<ListRoleMembersApiRolesRoleIdMembersGetResponse, ListRoleMembersApiRolesRoleIdMembersGetError, ListRoleMembersApiRolesRoleIdMembersGetResponse, ReturnType<typeof listRoleMembersApiRolesRoleIdMembersGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listRoleMembersApiRolesRoleIdMembersGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listRoleMembersApiRolesRoleIdMembersGetQueryKey(options)
});

/**
 * Add Role Member
 *
 * Add member to role. Admin only.
 */
export const addRoleMemberApiRolesRoleIdMembersPostMutation = (options?: Partial<Options<AddRoleMemberApiRolesRoleIdMembersPostData>>): UseMutationOptions<AddRoleMemberApiRolesRoleIdMembersPostResponse, AddRoleMemberApiRolesRoleIdMembersPostError, Options<AddRoleMemberApiRolesRoleIdMembersPostData>> => {
    const mutationOptions: UseMutationOptions<AddRoleMemberApiRolesRoleIdMembersPostResponse, AddRoleMemberApiRolesRoleIdMembersPostError, Options<AddRoleMemberApiRolesRoleIdMembersPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await addRoleMemberApiRolesRoleIdMembersPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Remove Role Member
 *
 * Remove member from role. Admin only.
 */
export const removeRoleMemberApiRolesRoleIdMembersUserIdDeleteMutation = (options?: Partial<Options<RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteData>>): UseMutationOptions<RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteResponse, RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteError, Options<RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteData>> => {
    const mutationOptions: UseMutationOptions<RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteResponse, RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteError, Options<RemoveRoleMemberApiRolesRoleIdMembersUserIdDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await removeRoleMemberApiRolesRoleIdMembersUserIdDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const rootGetQueryKey = (options?: Options<RootGetData>) => createQueryKey('rootGet', options);

/**
 * Root
 */
export const rootGetOptions = (options?: Options<RootGetData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof rootGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await rootGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: rootGetQueryKey(options)
});

export const healthHealthGetQueryKey = (options?: Options<HealthHealthGetData>) => createQueryKey('healthHealthGet', options);

/**
 * Health
 */
export const healthHealthGetOptions = (options?: Options<HealthHealthGetData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof healthHealthGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthHealthGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthHealthGetQueryKey(options)
});
