"""
Rename User to ChatUser.

Revision ID: 81bc101ee96c
Revises: 8f8b563a0085
Create Date: 2024-11-16 02:33:11.449246

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '81bc101ee96c'
down_revision: str | None = '8f8b563a0085'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrades db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_id', table_name='users')
    op.rename_table('users', 'chat_users')
    op.create_index(op.f('ix_chat_users_id'), 'chat_users', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_users_id'), table_name='chat_users')
    op.rename_table('chat_users', 'users')
    op.create_index('ix_users_id', 'chat_users', ['id'], unique=True)
    # ### end Alembic commands ###
