"""Added name to GlWebhook.

Revision ID: ea513061063e
Revises: 1e6d9bd7b99a
Create Date: 2025-06-21 00:44:20.202983

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ea513061063e"
down_revision: Union[str, None] = "1e6d9bd7b99a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrades db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gl_webhooks", sa.Column("name", sa.String(), server_default="", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gl_webhooks", "name")
    # ### end Alembic commands ###
