"""Add LogEntry model for audit logging.

Revision ID: f8c2ca9171ff
Revises: 9e2c02f3f28b
Create Date: 2025-12-04 19:53:06.708777

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f8c2ca9171ff"
down_revision: Union[str, None] = "9e2c02f3f28b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrades db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "log_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "actor_type",
            sa.Enum("WEB_USER", "BOT_USER", "SYSTEM", name="actortype"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.String(), nullable=True),
        sa.Column(
            "action_type",
            sa.Enum(
                "CREATE", "UPDATE", "DELETE", "ASSIGN", "UNASSIGN", name="actiontype"
            ),
            nullable=False,
        ),
        sa.Column(
            "entity_type",
            sa.Enum(
                "USER",
                "CHAT_USER",
                "ROLE",
                "CHAT",
                "ROLE_ASSIGNMENT",
                "CHAT_MEMBERSHIP",
                "BOT_SETTINGS",
                name="entitytype",
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("web_user_username", sa.String(), nullable=True),
        sa.Column("bot_user_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bot_user_id"], ["chat_users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["web_user_username"], ["users.username"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_log_entries_action_type"), "log_entries", ["action_type"], unique=False
    )
    op.create_index(
        op.f("ix_log_entries_actor_id"), "log_entries", ["actor_id"], unique=False
    )
    op.create_index(
        op.f("ix_log_entries_actor_type"), "log_entries", ["actor_type"], unique=False
    )
    op.create_index(
        op.f("ix_log_entries_bot_user_id"), "log_entries", ["bot_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_log_entries_entity_type"), "log_entries", ["entity_type"], unique=False
    )
    op.create_index(
        op.f("ix_log_entries_timestamp"), "log_entries", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_log_entries_web_user_username"),
        "log_entries",
        ["web_user_username"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_log_entries_web_user_username"), table_name="log_entries")
    op.drop_index(op.f("ix_log_entries_timestamp"), table_name="log_entries")
    op.drop_index(op.f("ix_log_entries_entity_type"), table_name="log_entries")
    op.drop_index(op.f("ix_log_entries_bot_user_id"), table_name="log_entries")
    op.drop_index(op.f("ix_log_entries_actor_type"), table_name="log_entries")
    op.drop_index(op.f("ix_log_entries_actor_id"), table_name="log_entries")
    op.drop_index(op.f("ix_log_entries_action_type"), table_name="log_entries")
    op.drop_table("log_entries")
    # ### end Alembic commands ###
