"""Added GlWebhook table.

Revision ID: 1e6d9bd7b99a
Revises: 4d86f9393db7
Create Date: 2025-06-18 23:20:47.169856

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1e6d9bd7b99a"
down_revision: Union[str, None] = "4d86f9393db7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrades db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gl_webhooks",
        sa.Column("hashed_secret", sa.String(), nullable=False),
        sa.Column("chat_id", sa.String(), nullable=False),
        sa.Column("created_by_id", sa.String(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["chat_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gl_webhooks_id"), "gl_webhooks", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gl_webhooks_id"), table_name="gl_webhooks")
    op.drop_table("gl_webhooks")
    # ### end Alembic commands ###
