"""chat user name.

Revision ID: 4d520a5b73f9
Revises: 031d506b0672
Create Date: 2026-09-09 18:52:19.899376

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d520a5b73f9"
down_revision: Union[str, None] = "031d506b0672"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrades db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_users", sa.Column("first_name", sa.String(), nullable=True))
    op.add_column("chat_users", sa.Column("last_name", sa.String(), nullable=True))
    op.add_column("chat_users", sa.Column("nick", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_users", "nick")
    op.drop_column("chat_users", "last_name")
    op.drop_column("chat_users", "first_name")
    # ### end Alembic commands ###
