"""add webhooks table.

Revision ID: 2cdc464cdee9
Revises: 7383432e5c3e
Create Date: 2026-01-26 17:38:35.278581

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2cdc464cdee9"
down_revision: Union[str, None] = "7383432e5c3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrades db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhooks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("chat_id", sa.String(), nullable=False),
        sa.Column("api_key_hash", sa.String(length=255), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("webhook_metadata", sa.JSON(), server_default="{}", nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["chat_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webhooks_api_key_hash"), "webhooks", ["api_key_hash"], unique=True
    )
    op.create_index(op.f("ix_webhooks_chat_id"), "webhooks", ["chat_id"], unique=False)
    op.create_index(
        op.f("ix_webhooks_created_by"), "webhooks", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_webhooks_name"), "webhooks", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_webhooks_name"), table_name="webhooks")
    op.drop_index(op.f("ix_webhooks_created_by"), table_name="webhooks")
    op.drop_index(op.f("ix_webhooks_chat_id"), table_name="webhooks")
    op.drop_index(op.f("ix_webhooks_api_key_hash"), table_name="webhooks")
    op.drop_table("webhooks")
    # ### end Alembic commands ###
