"""Testing.

Revision ID: 7383432e5c3e
Revises: f8c2ca9171ff
Create Date: 2026-01-14 21:40:02.199784

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7383432e5c3e"
down_revision: Union[str, None] = "f8c2ca9171ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrades db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_history",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["chat_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_login_history_id"), "login_history", ["id"], unique=True)
    op.create_table(
        "login_tokens",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column(
            "used", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["chat_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_login_tokens_id"), "login_tokens", ["id"], unique=True)
    op.create_index(
        op.f("ix_login_tokens_token"), "login_tokens", ["token"], unique=True
    )
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_constraint(
        op.f("log_entries_web_user_username_fkey"), "log_entries", type_="foreignkey"
    )
    op.drop_table("users")
    op.add_column(
        "chat_users",
        sa.Column(
            "is_superuser",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "chat_users",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_users", "created_at")
    op.drop_column("chat_users", "is_superuser")
    op.create_table(
        "users",
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("hashed_password", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_superuser",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("username", name=op.f("users_pkey1")),
    )
    op.create_foreign_key(
        op.f("log_entries_web_user_username_fkey"),
        "log_entries",
        "users",
        ["web_user_username"],
        ["username"],
        ondelete="SET NULL",
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.drop_index(op.f("ix_login_tokens_token"), table_name="login_tokens")
    op.drop_index(op.f("ix_login_tokens_id"), table_name="login_tokens")
    op.drop_table("login_tokens")
    op.drop_index(op.f("ix_login_history_id"), table_name="login_history")
    op.drop_table("login_history")
    # ### end Alembic commands ###
