"""chat user is_bot.

Revision ID: 031d506b0672
Revises: 67484ed5d10c
Create Date: 2026-09-09 18:43:26.557929

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "031d506b0672"
down_revision: Union[str, None] = "67484ed5d10c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrades db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_users",
        sa.Column(
            "is_bot", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_users", "is_bot")
    # ### end Alembic commands ###
