"""chat info.

Revision ID: b35d4c449bb0
Revises: d7e8f9a0b1c2
Create Date: 2026-09-11 12:17:35.981209

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b35d4c449bb0"
down_revision: Union[str, None] = "d7e8f9a0b1c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrades db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_users", sa.Column("about", sa.Text(), nullable=True))
    op.add_column("chat_users", sa.Column("photo_url", sa.String(), nullable=True))
    op.add_column(
        "chat_users", sa.Column("info_updated_at", sa.DateTime(), nullable=True)
    )
    op.add_column("chats", sa.Column("about", sa.Text(), nullable=True))
    op.add_column("chats", sa.Column("rules", sa.Text(), nullable=True))
    op.add_column("chats", sa.Column("invite_link", sa.String(), nullable=True))
    op.add_column("chats", sa.Column("public", sa.Boolean(), nullable=True))
    op.add_column("chats", sa.Column("join_moderation", sa.Boolean(), nullable=True))
    op.add_column("chats", sa.Column("info_updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "info_updated_at")
    op.drop_column("chats", "join_moderation")
    op.drop_column("chats", "public")
    op.drop_column("chats", "invite_link")
    op.drop_column("chats", "rules")
    op.drop_column("chats", "about")
    op.drop_column("chat_users", "info_updated_at")
    op.drop_column("chat_users", "photo_url")
    op.drop_column("chat_users", "about")
    # ### end Alembic commands ###
