"""chat title.

Revision ID: 67484ed5d10c
Revises: 2cdc464cdee9
Create Date: 2026-09-09 17:58:34.030717

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "67484ed5d10c"
down_revision: Union[str, None] = "2cdc464cdee9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrades db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("title", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "title")
    # ### end Alembic commands ###
