version: 1
disable_existing_loggers: false
formatters:
  standard:
    format: '[%(levelname)s %(asctime)s]: %(filename)s:%(lineno)s %(message)s'
  json:
    '()': 'vkt_bot.utils.formatters.JsonFormatter'
    fmt_keys:
      level: levelname
      message: message
      timestamp: timestamp
      logger: name
      module: module
      function: funcName
      line: lineno
      thread_name: threadName

root:
  level: WARNING
  handlers: [stderr]

handlers:
  stderr:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stderr
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: /dev/null
    maxBytes: 1000000
    backupCount: 3

loggers:
  teams_bot:
    level: INFO # TODO: fix
  passlib:
    level: ERROR
